/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param usedIn 
 * @param chargeIntervalDays 
 * @param rowCreatedTimestamp 
 * @param userfields Key/value pairs of userfields
 */
@Serializable

data class Battery (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "used_in") val usedIn: kotlin.String? = null,

    @SerialName(value = "charge_interval_days") val chargeIntervalDays: kotlin.Int? = 0,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.String? = null,

    /* Key/value pairs of userfields */
    @SerialName(value = "userfields") val userfields: kotlin.String? = null

) {


}

