/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param trackedTime The time of when the chore was executed, when omitted, the current time is used
 * @param doneBy A valid user id of who executed this chore, when omitted, the currently authenticated user will be used
 * @param skipped `true` when the execution should be tracked as skipped, defaults to `false` when omitted
 */
@Serializable

data class ChoresChoreIdExecutePostRequest (

    /* The time of when the chore was executed, when omitted, the current time is used */
    @SerialName(value = "tracked_time") val trackedTime: kotlin.time.Instant? = null,

    /* A valid user id of who executed this chore, when omitted, the currently authenticated user will be used */
    @SerialName(value = "done_by") val doneBy: kotlin.Int? = null,

    /* `true` when the execution should be tracked as skipped, defaults to `false` when omitted */
    @SerialName(value = "skipped") val skipped: kotlin.Boolean? = false

) {


}

