/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param periodType 
 * @param periodConfig 
 * @param periodDays 
 * @param trackDateOnly 
 * @param rollover 
 * @param assignmentType 
 * @param assignmentConfig 
 * @param nextExecutionAssignedToUserId 
 * @param startDate 
 * @param rescheduledDate 
 * @param rescheduledNextExecutionAssignedToUserId 
 * @param rowCreatedTimestamp 
 * @param userfields Key/value pairs of userfields
 */
@Serializable

data class Chore (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "period_type") val periodType: Chore.PeriodType? = null,

    @SerialName(value = "period_config") val periodConfig: kotlin.String? = null,

    @SerialName(value = "period_days") val periodDays: kotlin.Int? = null,

    @SerialName(value = "track_date_only") val trackDateOnly: kotlin.Int? = null,

    @SerialName(value = "rollover") val rollover: kotlin.Int? = null,

    @SerialName(value = "assignment_type") val assignmentType: Chore.AssignmentType? = null,

    @SerialName(value = "assignment_config") val assignmentConfig: kotlin.String? = null,

    @SerialName(value = "next_execution_assigned_to_user_id") val nextExecutionAssignedToUserId: kotlin.Int? = null,

    @SerialName(value = "start_date") val startDate: kotlin.String? = null,

    @SerialName(value = "rescheduled_date") val rescheduledDate: kotlin.String? = null,

    @SerialName(value = "rescheduled_next_execution_assigned_to_user_id") val rescheduledNextExecutionAssignedToUserId: kotlin.Int? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.String? = null,

    /* Key/value pairs of userfields */
    @SerialName(value = "userfields") val userfields: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: manually,hourly,daily,weekly,monthly
     */
    @Serializable
    enum class PeriodType(val value: kotlin.String) {
        @SerialName(value = "manually") manually("manually"),
        @SerialName(value = "hourly") hourly("hourly"),
        @SerialName(value = "daily") daily("daily"),
        @SerialName(value = "weekly") weekly("weekly"),
        @SerialName(value = "monthly") monthly("monthly");
    }
    /**
     * 
     *
     * Values: noMinusAssignment,whoMinusLeastMinusDidMinusFirst,random,inMinusAlphabeticalMinusOrder
     */
    @Serializable
    enum class AssignmentType(val value: kotlin.String) {
        @SerialName(value = "no-assignment") noMinusAssignment("no-assignment"),
        @SerialName(value = "who-least-did-first") whoMinusLeastMinusDidMinusFirst("who-least-did-first"),
        @SerialName(value = "random") random("random"),
        @SerialName(value = "in-alphabetical-order") inMinusAlphabeticalMinusOrder("in-alphabetical-order");
    }

}

