/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.Chore
import org.openapitools.client.models.UserDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param chore 
 * @param lastTracked When this chore was last tracked
 * @param trackCount How often this chore was tracked so far
 * @param lastDoneBy 
 * @param nextEstimatedExecutionTime 
 * @param nextExecutionAssignedUser 
 * @param averageExecutionFrequencyHours Contains the average past execution frequency in hours or `null`, when the chore was never executed before
 */
@Serializable

data class ChoreDetailsResponse (

    @SerialName(value = "chore") val chore: Chore? = null,

    /* When this chore was last tracked */
    @SerialName(value = "last_tracked") val lastTracked: kotlin.time.Instant? = null,

    /* How often this chore was tracked so far */
    @SerialName(value = "track_count") val trackCount: kotlin.Int? = null,

    @SerialName(value = "last_done_by") val lastDoneBy: UserDto? = null,

    @SerialName(value = "next_estimated_execution_time") val nextEstimatedExecutionTime: kotlin.time.Instant? = null,

    @SerialName(value = "next_execution_assigned_user") val nextExecutionAssignedUser: UserDto? = null,

    /* Contains the average past execution frequency in hours or `null`, when the chore was never executed before */
    @SerialName(value = "average_execution_frequency_hours") val averageExecutionFrequencyHours: kotlin.Int? = null

) {


}

