/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param amountMissing 
 * @param isPartlyInStock 
 */
@Serializable

data class CurrentVolatilStockResponseMissingProductsInner (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "amount_missing") val amountMissing: kotlin.Double? = null,

    @SerialName(value = "is_partly_in_stock") val isPartlyInStock: kotlin.Int? = null

) {


}

