/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param productId 
 * @param amount 
 * @param amountAggregated 
 * @param amountOpened 
 * @param amountOpenedAggregated 
 * @param bestBeforeDate The next due date for this product
 * @param isAggregatedAmount Indicates wheter this product has sub-products or not / if the fields `amount_aggregated` and `amount_opened_aggregated` are filled
 * @param product 
 */
@Serializable

data class CurrentStockResponse (

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "amount_aggregated") val amountAggregated: kotlin.Double? = null,

    @SerialName(value = "amount_opened") val amountOpened: kotlin.Double? = null,

    @SerialName(value = "amount_opened_aggregated") val amountOpenedAggregated: kotlin.Double? = null,

    /* The next due date for this product */
    @SerialName(value = "best_before_date") val bestBeforeDate: kotlinx.datetime.LocalDate? = null,

    /* Indicates wheter this product has sub-products or not / if the fields `amount_aggregated` and `amount_opened_aggregated` are filled */
    @SerialName(value = "is_aggregated_amount") val isAggregatedAmount: kotlin.Int? = null,

    @SerialName(value = "product") val product: ProductWithoutUserfields? = null

) {


}

