/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.CurrentStockResponse
import org.openapitools.client.models.CurrentVolatilStockResponseMissingProductsInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dueProducts 
 * @param overdueProducts 
 * @param expiredProducts 
 * @param missingProducts 
 */
@Serializable

data class CurrentVolatilStockResponse (

    @SerialName(value = "due_products") val dueProducts: kotlin.collections.List<CurrentStockResponse>? = null,

    @SerialName(value = "overdue_products") val overdueProducts: kotlin.collections.List<CurrentStockResponse>? = null,

    @SerialName(value = "expired_products") val expiredProducts: kotlin.collections.List<CurrentStockResponse>? = null,

    @SerialName(value = "missing_products") val missingProducts: kotlin.collections.List<CurrentVolatilStockResponseMissingProductsInner>? = null

) {


}

