/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param choreId 
 * @param choreName 
 * @param lastTrackedTime 
 * @param trackDateOnly 
 * @param nextEstimatedExecutionTime The next estimated execution time of this chore, 2999-12-31 23:59:59 when the given chore has a period_type of manually
 * @param nextExecutionAssignedToUserId 
 * @param isRescheduled 
 * @param isReassigned 
 * @param nextExecutionAssignedUser 
 */
@Serializable

data class CurrentChoreResponse (

    @SerialName(value = "chore_id") val choreId: kotlin.Int? = null,

    @SerialName(value = "chore_name") val choreName: kotlin.String? = null,

    @SerialName(value = "last_tracked_time") val lastTrackedTime: kotlin.time.Instant? = null,

    @SerialName(value = "track_date_only") val trackDateOnly: kotlin.Boolean? = null,

    /* The next estimated execution time of this chore, 2999-12-31 23:59:59 when the given chore has a period_type of manually */
    @SerialName(value = "next_estimated_execution_time") val nextEstimatedExecutionTime: kotlin.time.Instant? = null,

    @SerialName(value = "next_execution_assigned_to_user_id") val nextExecutionAssignedToUserId: kotlin.Int? = null,

    @SerialName(value = "is_rescheduled") val isRescheduled: kotlin.Boolean? = null,

    @SerialName(value = "is_reassigned") val isReassigned: kotlin.Boolean? = null,

    @SerialName(value = "next_execution_assigned_user") val nextExecutionAssignedUser: UserDto? = null

) {


}

