/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.TaskCategory
import org.openapitools.client.models.UserDto

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param dueDate 
 * @param done 
 * @param doneTimestamp 
 * @param categoryId 
 * @param assignedToUserId 
 * @param rowCreatedTimestamp 
 * @param assignedToUser 
 * @param category 
 */
@Serializable

data class CurrentTaskResponse (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "due_date") val dueDate: kotlin.time.Instant? = null,

    @SerialName(value = "done") val done: kotlin.Int? = null,

    @SerialName(value = "done_timestamp") val doneTimestamp: kotlin.time.Instant? = null,

    @SerialName(value = "category_id") val categoryId: kotlin.Int? = null,

    @SerialName(value = "assigned_to_user_id") val assignedToUserId: kotlin.Int? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.time.Instant? = null,

    @SerialName(value = "assigned_to_user") val assignedToUser: UserDto? = null,

    @SerialName(value = "category") val category: TaskCategory? = null

) {


}

