/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param batteryId 
 * @param lastTrackedTime 
 * @param nextEstimatedChargeTime The next estimated charge time of this battery, 2999-12-31 23:59:59 when the given battery has no charge_interval_days defined
 */
@Serializable

data class CurrentBatteryResponse (

    @SerialName(value = "battery_id") val batteryId: kotlin.Int? = null,

    @SerialName(value = "last_tracked_time") val lastTrackedTime: kotlin.time.Instant? = null,

    /* The next estimated charge time of this battery, 2999-12-31 23:59:59 when the given battery has no charge_interval_days defined */
    @SerialName(value = "next_estimated_charge_time") val nextEstimatedChargeTime: kotlin.time.Instant? = null

) {


}

