/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: stock_log,api_keys,stock,stock_current_locations,chores_log,products_last_purchased,products_average_price,quantity_unit_conversions_resolved,recipes_pos_resolved,battery_charge_cycles,product_barcodes_view,permission_hierarchy
 */
@Serializable
enum class ExposedEntityNoEdit(val value: kotlin.String) {

    @SerialName(value = "stock_log")
    stock_log("stock_log"),

    @SerialName(value = "api_keys")
    api_keys("api_keys"),

    @SerialName(value = "stock")
    stock("stock"),

    @SerialName(value = "stock_current_locations")
    stock_current_locations("stock_current_locations"),

    @SerialName(value = "chores_log")
    chores_log("chores_log"),

    @SerialName(value = "products_last_purchased")
    products_last_purchased("products_last_purchased"),

    @SerialName(value = "products_average_price")
    products_average_price("products_average_price"),

    @SerialName(value = "quantity_unit_conversions_resolved")
    quantity_unit_conversions_resolved("quantity_unit_conversions_resolved"),

    @SerialName(value = "recipes_pos_resolved")
    recipes_pos_resolved("recipes_pos_resolved"),

    @SerialName(value = "battery_charge_cycles")
    battery_charge_cycles("battery_charge_cycles"),

    @SerialName(value = "product_barcodes_view")
    product_barcodes_view("product_barcodes_view"),

    @SerialName(value = "permission_hierarchy")
    permission_hierarchy("permission_hierarchy");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ExposedEntityNoEdit) "$data" else null

        /**
         * Returns a valid [ExposedEntityNoEdit] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ExposedEntityNoEdit? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

