/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: products,chores,product_barcodes,batteries,locations,quantity_units,quantity_unit_conversions,shopping_list,shopping_lists,shopping_locations,recipes,recipes_pos,recipes_nestings,tasks,task_categories,product_groups,equipment,api_keys,userfields,userentities,userobjects,meal_plan,stock_log,stock,stock_current_locations,chores_log,meal_plan_sections,products_last_purchased,products_average_price,quantity_unit_conversions_resolved,recipes_pos_resolved,battery_charge_cycles,product_barcodes_view,permission_hierarchy
 */
@Serializable
enum class ExposedEntity(val value: kotlin.String) {

    @SerialName(value = "products")
    products("products"),

    @SerialName(value = "chores")
    chores("chores"),

    @SerialName(value = "product_barcodes")
    product_barcodes("product_barcodes"),

    @SerialName(value = "batteries")
    batteries("batteries"),

    @SerialName(value = "locations")
    locations("locations"),

    @SerialName(value = "quantity_units")
    quantity_units("quantity_units"),

    @SerialName(value = "quantity_unit_conversions")
    quantity_unit_conversions("quantity_unit_conversions"),

    @SerialName(value = "shopping_list")
    shopping_list("shopping_list"),

    @SerialName(value = "shopping_lists")
    shopping_lists("shopping_lists"),

    @SerialName(value = "shopping_locations")
    shopping_locations("shopping_locations"),

    @SerialName(value = "recipes")
    recipes("recipes"),

    @SerialName(value = "recipes_pos")
    recipes_pos("recipes_pos"),

    @SerialName(value = "recipes_nestings")
    recipes_nestings("recipes_nestings"),

    @SerialName(value = "tasks")
    tasks("tasks"),

    @SerialName(value = "task_categories")
    task_categories("task_categories"),

    @SerialName(value = "product_groups")
    product_groups("product_groups"),

    @SerialName(value = "equipment")
    equipment("equipment"),

    @SerialName(value = "api_keys")
    api_keys("api_keys"),

    @SerialName(value = "userfields")
    userfields("userfields"),

    @SerialName(value = "userentities")
    userentities("userentities"),

    @SerialName(value = "userobjects")
    userobjects("userobjects"),

    @SerialName(value = "meal_plan")
    meal_plan("meal_plan"),

    @SerialName(value = "stock_log")
    stock_log("stock_log"),

    @SerialName(value = "stock")
    stock("stock"),

    @SerialName(value = "stock_current_locations")
    stock_current_locations("stock_current_locations"),

    @SerialName(value = "chores_log")
    chores_log("chores_log"),

    @SerialName(value = "meal_plan_sections")
    meal_plan_sections("meal_plan_sections"),

    @SerialName(value = "products_last_purchased")
    products_last_purchased("products_last_purchased"),

    @SerialName(value = "products_average_price")
    products_average_price("products_average_price"),

    @SerialName(value = "quantity_unit_conversions_resolved")
    quantity_unit_conversions_resolved("quantity_unit_conversions_resolved"),

    @SerialName(value = "recipes_pos_resolved")
    recipes_pos_resolved("recipes_pos_resolved"),

    @SerialName(value = "battery_charge_cycles")
    battery_charge_cycles("battery_charge_cycles"),

    @SerialName(value = "product_barcodes_view")
    product_barcodes_view("product_barcodes_view"),

    @SerialName(value = "permission_hierarchy")
    permission_hierarchy("permission_hierarchy");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ExposedEntity) "$data" else null

        /**
         * Returns a valid [ExposedEntity] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ExposedEntity? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

