/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param locationId 
 * @param quIdPurchase 
 * @param quIdStock 
 * @param quFactorPurchaseToStock 
 * @param barcode Can contain multiple barcodes separated by comma
 * @param id The id of the added product, only included when the producted was added to the database
 */
@Serializable

data class ExternalBarcodeLookupResponse (

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    @SerialName(value = "qu_id_purchase") val quIdPurchase: kotlin.Int? = null,

    @SerialName(value = "qu_id_stock") val quIdStock: kotlin.Int? = null,

    @SerialName(value = "qu_factor_purchase_to_stock") val quFactorPurchaseToStock: kotlin.Double? = null,

    /* Can contain multiple barcodes separated by comma */
    @SerialName(value = "barcode") val barcode: kotlin.String? = null,

    /* The id of the added product, only included when the producted was added to the database */
    @SerialName(value = "id") val id: kotlin.Int? = null

) {


}

