/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.Location
import org.openapitools.client.models.Product
import org.openapitools.client.models.ProductBarcode
import org.openapitools.client.models.QuantityUnit

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param product 
 * @param productBarcodes 
 * @param quantityUnitStock 
 * @param defaultQuantityUnitPurchase 
 * @param defaultQuantityUnitConsume 
 * @param quantityUnitPrice 
 * @param lastPurchased 
 * @param lastUsed 
 * @param stockAmount 
 * @param stockAmountOpened 
 * @param nextDueDate 
 * @param lastPrice The price of the last purchase of the corresponding product
 * @param avgPrice The average price af all stock entries currently in stock of the corresponding product
 * @param currentPrice The current price of the corresponding product, based on the stock entry to use next (defined by the default consume rule \"Opened first, then first due first, then first in first out\") or on the last price if the product is currently not in stock
 * @param oldestPrice This field is deprecated and will be removed in a future version (currently returns the same as `current_price`)
 * @param lastShoppingLocationId 
 * @param location 
 * @param averageShelfLifeDays 
 * @param spoilRatePercent 
 * @param hasChilds True when the product is a parent product of others
 * @param defaultLocation 
 * @param quConversionFactorPurchaseToStock The conversion factor of the corresponding QU conversion from the product's qu_id_purchase to qu_id_stock
 * @param quConversionFactorPriceToStock The conversion factor of the corresponding QU conversion from the product's qu_id_price to qu_id_stock
 */
@Serializable

data class ProductDetailsResponse (

    @SerialName(value = "product") val product: Product? = null,

    @SerialName(value = "product_barcodes") val productBarcodes: kotlin.collections.List<ProductBarcode>? = null,

    @SerialName(value = "quantity_unit_stock") val quantityUnitStock: QuantityUnit? = null,

    @SerialName(value = "default_quantity_unit_purchase") val defaultQuantityUnitPurchase: QuantityUnit? = null,

    @SerialName(value = "default_quantity_unit_consume") val defaultQuantityUnitConsume: QuantityUnit? = null,

    @SerialName(value = "quantity_unit_price") val quantityUnitPrice: QuantityUnit? = null,

    @SerialName(value = "last_purchased") val lastPurchased: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "last_used") val lastUsed: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "stock_amount") val stockAmount: kotlin.Double? = null,

    @SerialName(value = "stock_amount_opened") val stockAmountOpened: kotlin.Double? = null,

    @SerialName(value = "next_due_date") val nextDueDate: kotlinx.datetime.LocalDate? = null,

    /* The price of the last purchase of the corresponding product */
    @SerialName(value = "last_price") val lastPrice: kotlin.Double? = null,

    /* The average price af all stock entries currently in stock of the corresponding product */
    @SerialName(value = "avg_price") val avgPrice: kotlin.Double? = null,

    /* The current price of the corresponding product, based on the stock entry to use next (defined by the default consume rule \"Opened first, then first due first, then first in first out\") or on the last price if the product is currently not in stock */
    @SerialName(value = "current_price") val currentPrice: kotlin.Double? = null,

    /* This field is deprecated and will be removed in a future version (currently returns the same as `current_price`) */
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "oldest_price") val oldestPrice: kotlin.Double? = null,

    @SerialName(value = "last_shopping_location_id") val lastShoppingLocationId: kotlin.Int? = null,

    @SerialName(value = "location") val location: Location? = null,

    @SerialName(value = "average_shelf_life_days") val averageShelfLifeDays: kotlin.Double? = null,

    @SerialName(value = "spoil_rate_percent") val spoilRatePercent: kotlin.Double? = null,

    /* True when the product is a parent product of others */
    @SerialName(value = "has_childs") val hasChilds: kotlin.Boolean? = null,

    @SerialName(value = "default_location") val defaultLocation: Location? = null,

    /* The conversion factor of the corresponding QU conversion from the product's qu_id_purchase to qu_id_stock */
    @SerialName(value = "qu_conversion_factor_purchase_to_stock") val quConversionFactorPurchaseToStock: kotlin.Double? = null,

    /* The conversion factor of the corresponding QU conversion from the product's qu_id_price to qu_id_stock */
    @SerialName(value = "qu_conversion_factor_price_to_stock") val quConversionFactorPriceToStock: kotlin.Double? = null

) {


}

