/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param locationId 
 * @param quIdPurchase 
 * @param quIdStock 
 * @param enableTareWeightHandling 
 * @param notCheckStockFulfillmentForRecipes 
 * @param productGroupId 
 * @param tareWeight 
 * @param minStockAmount 
 * @param defaultBestBeforeDays 
 * @param defaultBestBeforeDaysAfterOpen 
 * @param pictureFileName 
 * @param rowCreatedTimestamp 
 * @param shoppingLocationId 
 * @param treatOpenedAsOutOfStock 
 * @param autoReprintStockLabel 
 * @param noOwnStock 
 * @param userfields Key/value pairs of userfields
 * @param shouldNotBeFrozen 
 * @param defaultConsumeLocationId 
 * @param moveOnOpen 
 */
@Serializable

data class Product (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    @SerialName(value = "qu_id_purchase") val quIdPurchase: kotlin.Int? = null,

    @SerialName(value = "qu_id_stock") val quIdStock: kotlin.Int? = null,

    @SerialName(value = "enable_tare_weight_handling") val enableTareWeightHandling: kotlin.Int? = null,

    @SerialName(value = "not_check_stock_fulfillment_for_recipes") val notCheckStockFulfillmentForRecipes: kotlin.Int? = null,

    @SerialName(value = "product_group_id") val productGroupId: kotlin.Int? = null,

    @SerialName(value = "tare_weight") val tareWeight: kotlin.Double? = null,

    @SerialName(value = "min_stock_amount") val minStockAmount: kotlin.Double? = (0).toDouble(),

    @SerialName(value = "default_best_before_days") val defaultBestBeforeDays: kotlin.Int? = 0,

    @SerialName(value = "default_best_before_days_after_open") val defaultBestBeforeDaysAfterOpen: kotlin.Int? = 0,

    @SerialName(value = "picture_file_name") val pictureFileName: kotlin.String? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.time.Instant? = null,

    @SerialName(value = "shopping_location_id") val shoppingLocationId: kotlin.Int? = null,

    @SerialName(value = "treat_opened_as_out_of_stock") val treatOpenedAsOutOfStock: kotlin.Int? = null,

    @SerialName(value = "auto_reprint_stock_label") val autoReprintStockLabel: kotlin.Int? = null,

    @SerialName(value = "no_own_stock") val noOwnStock: kotlin.Int? = null,

    /* Key/value pairs of userfields */
    @SerialName(value = "userfields") val userfields: kotlin.String? = null,

    @SerialName(value = "should_not_be_frozen") val shouldNotBeFrozen: kotlin.Int? = null,

    @SerialName(value = "default_consume_location_id") val defaultConsumeLocationId: kotlin.Int? = null,

    @SerialName(value = "move_on_open") val moveOnOpen: kotlin.Int? = null

) {


}

