/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param productId 
 * @param barcode 
 * @param quId 
 * @param shoppingLocationId 
 * @param amount 
 * @param lastPrice 
 * @param note 
 */
@Serializable

data class ProductBarcode (

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "barcode") val barcode: kotlin.String? = null,

    @SerialName(value = "qu_id") val quId: kotlin.Int? = null,

    @SerialName(value = "shopping_location_id") val shoppingLocationId: kotlin.Int? = null,

    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "last_price") val lastPrice: kotlin.Double? = null,

    @SerialName(value = "note") val note: kotlin.String? = null

) {


}

