/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param date 
 * @param price 
 * @param shoppingLocation 
 */
@Serializable

data class ProductPriceHistory (

    @SerialName(value = "date") val date: kotlin.String? = null,

    @SerialName(value = "price") val price: kotlin.Double? = null,

    @SerialName(value = "shopping_location") val shoppingLocation: ShoppingLocation? = null

) {


}

