/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param namePlural 
 * @param description 
 * @param rowCreatedTimestamp 
 * @param pluralForms 
 * @param userfields Key/value pairs of userfields
 */
@Serializable

data class QuantityUnit (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "name_plural") val namePlural: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.time.Instant? = null,

    @SerialName(value = "plural_forms") val pluralForms: kotlin.String? = null,

    /* Key/value pairs of userfields */
    @SerialName(value = "userfields") val userfields: kotlin.String? = null

) {


}

