/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param excludedProductIds An optional array of product ids to exclude them from being put on the shopping list
 */
@Serializable

data class RecipesRecipeIdAddNotFulfilledProductsToShoppinglistPostRequest (

    /* An optional array of product ids to exclude them from being put on the shopping list */
    @SerialName(value = "excludedProductIds") val excludedProductIds: kotlin.collections.List<kotlin.Int>? = null

) {


}

