/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param recipeId 
 * @param needFulfilled 
 * @param needFulfilledWithShoppingList 
 * @param missingProductsCount 
 * @param costs 
 */
@Serializable

data class RecipeFulfillmentResponse (

    @SerialName(value = "recipe_id") val recipeId: kotlin.Int? = null,

    @SerialName(value = "need_fulfilled") val needFulfilled: kotlin.Boolean? = null,

    @SerialName(value = "need_fulfilled_with_shopping_list") val needFulfilledWithShoppingList: kotlin.Boolean? = null,

    @SerialName(value = "missing_products_count") val missingProductsCount: kotlin.Int? = null,

    @SerialName(value = "costs") val costs: kotlin.Double? = null

) {


}

