/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param sessionKey 
 * @param expires 
 * @param lastUsed 
 * @param rowCreatedTimestamp 
 */
@Serializable

data class Session (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "session_key") val sessionKey: kotlin.String? = null,

    @SerialName(value = "expires") val expires: kotlin.time.Instant? = null,

    @SerialName(value = "last_used") val lastUsed: kotlin.time.Instant? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.time.Instant? = null

) {


}

