/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param id 
 * @param shoppingListId 
 * @param productId 
 * @param note 
 * @param amount The manual entered amount
 * @param rowCreatedTimestamp 
 * @param userfields Key/value pairs of userfields
 */
@Serializable

data class ShoppingListItem (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "shopping_list_id") val shoppingListId: kotlin.Int? = null,

    // Manually added (see regenerate.sh): spec omits done on shopping_list rows, the server sends it as 0/1
    @SerialName(value = "done") val done: kotlin.Int? = null,

    // Manually added (see regenerate.sh): spec omits qu_id on shopping_list rows, the server sends it
    @SerialName(value = "qu_id") val quId: kotlin.Int? = null,

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "note") val note: kotlin.String? = null,

    /* The manual entered amount */
    @SerialName(value = "amount") val amount: kotlin.Double? = (0).toDouble(),

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.String? = null,

    /* Key/value pairs of userfields */
    // Manually corrected (see regenerate.sh): spec mistypes userfields as string, server sends a JSON object
    @SerialName(value = "userfields") val userfields: kotlinx.serialization.json.JsonElement? = null

) {


}

