/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param shoppingListId 
 * @param productId 
 * @param note 
 * @param amount The manual entered amount
 * @param rowCreatedTimestamp 
 * @param userfields Key/value pairs of userfields
 */
@Serializable

data class ShoppingListItem (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "shopping_list_id") val shoppingListId: kotlin.Int? = null,

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "note") val note: kotlin.String? = null,

    /* The manual entered amount */
    @SerialName(value = "amount") val amount: kotlin.Double? = (0).toDouble(),

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.time.Instant? = null,

    /* Key/value pairs of userfields */
    @SerialName(value = "userfields") val userfields: kotlin.String? = null

) {


}

