/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param newAmount The new current amount for the given product - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
 * @param bestBeforeDate The due date which applies to added products
 * @param shoppingLocationId If omitted, no store will be affected
 * @param locationId If omitted, the default location of the product is used (only applies to added products)
 * @param price If omitted, the last price of the product is used (only applies to added products)
 * @param stockLabelType `1` = No label, `2` = Single label, `3` = Label per unit (only applies to added products)
 * @param note An optional note for the corresponding stock entry (only applies to added products)
 */
@Serializable

data class StockProductsProductIdInventoryPostRequest (

    /* The new current amount for the given product - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight */
    @SerialName(value = "new_amount") val newAmount: kotlin.Double? = null,

    /* The due date which applies to added products */
    @SerialName(value = "best_before_date") val bestBeforeDate: kotlinx.datetime.LocalDate? = null,

    /* If omitted, no store will be affected */
    @SerialName(value = "shopping_location_id") val shoppingLocationId: kotlin.Int? = null,

    /* If omitted, the default location of the product is used (only applies to added products) */
    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    /* If omitted, the last price of the product is used (only applies to added products) */
    @SerialName(value = "price") val price: kotlin.Double? = null,

    /* `1` = No label, `2` = Single label, `3` = Label per unit (only applies to added products) */
    @SerialName(value = "stock_label_type") val stockLabelType: kotlin.Int? = null,

    /* An optional note for the corresponding stock entry (only applies to added products) */
    @SerialName(value = "note") val note: kotlin.String? = null

) {


}

