/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.StockTransactionType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param amount The amount to add - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
 * @param bestBeforeDate The due date of the product to add, when omitted, the current date is used
 * @param transactionType 
 * @param price The price per stock quantity unit in configured currency
 * @param locationId If omitted, the default location of the product is used
 * @param shoppingLocationId If omitted, no store will be affected
 * @param stockLabelType `1` = No label, `2` = Single label, `3` = Label per unit
 * @param note An optional note for the corresponding stock entry
 */
@Serializable

data class StockProductsProductIdAddPostRequest (

    /* The amount to add - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight */
    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    /* The due date of the product to add, when omitted, the current date is used */
    @SerialName(value = "best_before_date") val bestBeforeDate: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "transaction_type") val transactionType: StockTransactionType? = null,

    /* The price per stock quantity unit in configured currency */
    @SerialName(value = "price") val price: kotlin.Double? = null,

    /* If omitted, the default location of the product is used */
    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    /* If omitted, no store will be affected */
    @SerialName(value = "shopping_location_id") val shoppingLocationId: kotlin.Int? = null,

    /* `1` = No label, `2` = Single label, `3` = Label per unit */
    @SerialName(value = "stock_label_type") val stockLabelType: kotlin.Int? = null,

    /* An optional note for the corresponding stock entry */
    @SerialName(value = "note") val note: kotlin.String? = null

) {


}

