/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param id 
 * @param productId 
 * @param amount 
 * @param bestBeforeDate 
 * @param purchasedDate 
 * @param usedDate 
 * @param spoiled 
 * @param stockId 
 * @param transactionId 
 * @param transactionType 
 * @param note 
 * @param rowCreatedTimestamp 
 */
@Serializable

data class StockLogEntry (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "best_before_date") val bestBeforeDate: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "purchased_date") val purchasedDate: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "used_date") val usedDate: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "spoiled") val spoiled: kotlin.Int? = 0,

    @SerialName(value = "stock_id") val stockId: kotlin.String? = null,

    @SerialName(value = "transaction_id") val transactionId: kotlin.String? = null,

    @SerialName(value = "transaction_type") val transactionType: StockTransactionType? = null,

    @SerialName(value = "note") val note: kotlin.String? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.String? = null

) {


}

