/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param productId 
 * @param locationId 
 * @param shoppingLocationId 
 * @param amount 
 * @param bestBeforeDate 
 * @param purchasedDate 
 * @param stockId A unique id which references this stock entry during its lifetime
 * @param price 
 * @param `open` 
 * @param openedDate 
 * @param note 
 * @param rowCreatedTimestamp 
 */
@Serializable

data class StockEntry (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    @SerialName(value = "shopping_location_id") val shoppingLocationId: kotlin.Int? = null,

    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "best_before_date") val bestBeforeDate: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "purchased_date") val purchasedDate: kotlinx.datetime.LocalDate? = null,

    /* A unique id which references this stock entry during its lifetime */
    @SerialName(value = "stock_id") val stockId: kotlin.String? = null,

    @SerialName(value = "price") val price: kotlin.Double? = null,

    @SerialName(value = "open") val `open`: kotlin.Int? = null,

    @SerialName(value = "opened_date") val openedDate: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "note") val note: kotlin.String? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.time.Instant? = null

) {


}

