/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param amount The amount to transfer - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
 * @param locationIdFrom A valid location id, the location from where the product should be transfered
 * @param locationIdTo A valid location id, the location to where the product should be transfered
 * @param stockEntryId A specific stock entry id to transfer, if used, the amount has to be 1
 */
@Serializable

data class StockProductsProductIdTransferPostRequest (

    /* The amount to transfer - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight */
    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    /* A valid location id, the location from where the product should be transfered */
    @SerialName(value = "location_id_from") val locationIdFrom: kotlin.Int? = null,

    /* A valid location id, the location to where the product should be transfered */
    @SerialName(value = "location_id_to") val locationIdTo: kotlin.Int? = null,

    /* A specific stock entry id to transfer, if used, the amount has to be 1 */
    @SerialName(value = "stock_entry_id") val stockEntryId: kotlin.String? = null

) {


}

