/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.StockTransactionType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param correlationId 
 * @param undone 
 * @param undoneTimestamp 
 * @param amount 
 * @param locationId 
 * @param locationName 
 * @param productName 
 * @param quName 
 * @param quNamePlural 
 * @param userDisplayName 
 * @param spoiled 
 * @param transactionType 
 * @param rowCreatedTimestamp 
 */
@Serializable

data class StockJournal (

    @SerialName(value = "correlation_id") val correlationId: kotlin.String? = null,

    @SerialName(value = "undone") val undone: kotlin.Int? = null,

    @SerialName(value = "undone_timestamp") val undoneTimestamp: kotlin.time.Instant? = null,

    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    @SerialName(value = "location_name") val locationName: kotlin.String? = null,

    @SerialName(value = "product_name") val productName: kotlin.String? = null,

    @SerialName(value = "qu_name") val quName: kotlin.String? = null,

    @SerialName(value = "qu_name_plural") val quNamePlural: kotlin.String? = null,

    @SerialName(value = "user_display_name") val userDisplayName: kotlin.String? = null,

    @SerialName(value = "spoiled") val spoiled: kotlin.Boolean? = false,

    @SerialName(value = "transaction_type") val transactionType: StockTransactionType? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.time.Instant? = null

) {


}

