/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param productId A valid product id of the product to be added
 * @param quId A valid quantity unit id (used only for display; the amount needs to be related to the products stock QU), when omitted, the products stock QU is used
 * @param listId A valid shopping list id, when omitted, the default shopping list (with id 1) is used
 * @param productAmount The amount (related to the products stock QU) to add, when omitted, the default amount of 1 is used
 * @param note The note of the shopping list item
 */
@Serializable

data class StockShoppinglistAddProductPostRequest (

    /* A valid product id of the product to be added */
    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    /* A valid quantity unit id (used only for display; the amount needs to be related to the products stock QU), when omitted, the products stock QU is used */
    @SerialName(value = "qu_id") val quId: kotlin.Int? = null,

    /* A valid shopping list id, when omitted, the default shopping list (with id 1) is used */
    @SerialName(value = "list_id") val listId: kotlin.Int? = null,

    /* The amount (related to the products stock QU) to add, when omitted, the default amount of 1 is used */
    @SerialName(value = "product_amount") val productAmount: kotlin.Double? = null,

    /* The note of the shopping list item */
    @SerialName(value = "note") val note: kotlin.String? = null

) {


}

