/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param productId A valid product id of the item on the shopping list
 * @param listId A valid shopping list id, when omitted, the default shopping list (with id 1) is used
 * @param productAmount The amount of product units to remove, when omitted, the default amount of 1 is used
 */
@Serializable

data class StockShoppinglistRemoveProductPostRequest (

    /* A valid product id of the item on the shopping list */
    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    /* A valid shopping list id, when omitted, the default shopping list (with id 1) is used */
    @SerialName(value = "list_id") val listId: kotlin.Int? = null,

    /* The amount of product units to remove, when omitted, the default amount of 1 is used */
    @SerialName(value = "product_amount") val productAmount: kotlin.Double? = null

) {


}

