/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param listId The shopping list id to clear, when omitted, the default shopping list (with id 1) is used
 * @param doneOnly When `true`, only done items will be removed (defaults to `false` when ommited)
 */
@Serializable

data class StockShoppinglistClearPostRequest (

    /* The shopping list id to clear, when omitted, the default shopping list (with id 1) is used */
    @SerialName(value = "list_id") val listId: kotlin.Int? = null,

    /* When `true`, only done items will be removed (defaults to `false` when ommited) */
    @SerialName(value = "done_only") val doneOnly: kotlin.Boolean? = null

) {


}

