/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param amount The amount to remove - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
 * @param transactionType 
 * @param spoiled True when the given product was spoiled, defaults to false
 * @param stockEntryId A specific stock entry id to consume, if used, the amount has to be 1
 * @param recipeId A valid recipe id for which this product was used (for statistical purposes only)
 * @param locationId A valid location id (if supplied, only stock at the given location is considered, if ommitted, stock of any location is considered)
 * @param exactAmount For tare weight handling enabled products, `true` when the given is the absolute amount to be consumed, not the amount including the container weight
 * @param allowSubproductSubstitution `true` when any in stock sub product should be used when the given product is a parent product and currently not in stock
 */
@Serializable

data class StockProductsProductIdConsumePostRequest (

    /* The amount to remove - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight */
    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "transaction_type") val transactionType: StockTransactionType? = null,

    /* True when the given product was spoiled, defaults to false */
    @SerialName(value = "spoiled") val spoiled: kotlin.Int? = null,

    /* A specific stock entry id to consume, if used, the amount has to be 1 */
    @SerialName(value = "stock_entry_id") val stockEntryId: kotlin.String? = null,

    /* A valid recipe id for which this product was used (for statistical purposes only) */
    @SerialName(value = "recipe_id") val recipeId: kotlin.Int? = null,

    /* A valid location id (if supplied, only stock at the given location is considered, if ommitted, stock of any location is considered) */
    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    /* For tare weight handling enabled products, `true` when the given is the absolute amount to be consumed, not the amount including the container weight */
    @SerialName(value = "exact_amount") val exactAmount: kotlin.Int? = null,

    /* `true` when any in stock sub product should be used when the given product is a parent product and currently not in stock */
    @SerialName(value = "allow_subproduct_substitution") val allowSubproductSubstitution: kotlin.Int? = null

) {


}

