/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.StockTransactionType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param amount 
 * @param userId 
 * @param productName 
 * @param productId 
 * @param quName 
 * @param quNamePlural 
 * @param userDisplayName 
 * @param transactionType 
 */
@Serializable

data class StockJournalSummary (

    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    @SerialName(value = "user_id") val userId: kotlin.Int? = null,

    @SerialName(value = "product_name") val productName: kotlin.String? = null,

    @SerialName(value = "product_id") val productId: kotlin.Int? = null,

    @SerialName(value = "qu_name") val quName: kotlin.String? = null,

    @SerialName(value = "qu_name_plural") val quNamePlural: kotlin.String? = null,

    @SerialName(value = "user_display_name") val userDisplayName: kotlin.String? = null,

    @SerialName(value = "transaction_type") val transactionType: StockTransactionType? = null

) {


}

