/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param amount The amount to mark as opened
 * @param stockEntryId A specific stock entry id to open, if used, the amount has to be 1
 * @param allowSubproductSubstitution `rue` when any in stock sub product should be used when the given product is a parent product and currently not in stock
 */
@Serializable

data class StockProductsByBarcodeBarcodeOpenPostRequest (

    /* The amount to mark as opened */
    @SerialName(value = "amount") val amount: kotlin.Double? = null,

    /* A specific stock entry id to open, if used, the amount has to be 1 */
    @SerialName(value = "stock_entry_id") val stockEntryId: kotlin.String? = null,

    /* `rue` when any in stock sub product should be used when the given product is a parent product and currently not in stock */
    @SerialName(value = "allow_subproduct_substitution") val allowSubproductSubstitution: kotlin.Int? = null

) {


}

