/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import org.openapitools.client.models.SystemInfoGet200ResponseGrocyVersion

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param grocyVersion 
 * @param phpVersion 
 * @param sqliteVersion 
 */
@Serializable

data class SystemInfoGet200Response (

    @SerialName(value = "grocy_version") val grocyVersion: SystemInfoGet200ResponseGrocyVersion? = null,

    @SerialName(value = "php_version") val phpVersion: kotlin.String? = null,

    @SerialName(value = "sqlite_version") val sqliteVersion: kotlin.String? = null

) {


}

