/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param timezone 
 * @param timeLocal 
 * @param timeLocalSqlite3 
 * @param timeUtc 
 * @param timestamp 
 * @param offset 
 */
@Serializable

data class TimeResponse (

    @SerialName(value = "timezone") val timezone: kotlin.String? = null,

    @SerialName(value = "time_local") val timeLocal: kotlin.time.Instant? = null,

    @SerialName(value = "time_local_sqlite3") val timeLocalSqlite3: kotlin.time.Instant? = null,

    @SerialName(value = "time_utc") val timeUtc: kotlin.time.Instant? = null,

    @SerialName(value = "timestamp") val timestamp: kotlin.Int? = null,

    @SerialName(value = "offset") val offset: kotlin.Int? = null

) {


}

