/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A user object without the *password* and with an additional *display_name* property
 *
 * @param id 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param displayName 
 * @param pictureFileName 
 * @param rowCreatedTimestamp 
 */
@Serializable

data class UserDto (

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "username") val username: kotlin.String? = null,

    @SerialName(value = "first_name") val firstName: kotlin.String? = null,

    @SerialName(value = "last_name") val lastName: kotlin.String? = null,

    @SerialName(value = "display_name") val displayName: kotlin.String? = null,

    @SerialName(value = "picture_file_name") val pictureFileName: kotlin.String? = null,

    @SerialName(value = "row_created_timestamp") val rowCreatedTimestamp: kotlin.String? = null

) {


}

