/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ApiKey

class ApiKeyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiKey
        //val modelInstance = ApiKey()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `apiKey`
        should("test apiKey") {
            // uncomment below to test the property
            //modelInstance.apiKey shouldBe ("TODO")
        }

        // to test the property `expires`
        should("test expires") {
            // uncomment below to test the property
            //modelInstance.expires shouldBe ("TODO")
        }

        // to test the property `lastUsed`
        should("test lastUsed") {
            // uncomment below to test the property
            //modelInstance.lastUsed shouldBe ("TODO")
        }

        // to test the property `rowCreatedTimestamp`
        should("test rowCreatedTimestamp") {
            // uncomment below to test the property
            //modelInstance.rowCreatedTimestamp shouldBe ("TODO")
        }

    }
}
