/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BatteriesBatteryIdChargePostRequest

class BatteriesBatteryIdChargePostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatteriesBatteryIdChargePostRequest
        //val modelInstance = BatteriesBatteryIdChargePostRequest()

        // to test the property `trackedTime` - The time of when the battery was charged, when omitted, the current time is used
        should("test trackedTime") {
            // uncomment below to test the property
            //modelInstance.trackedTime shouldBe ("TODO")
        }

    }
}
