/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BatteryChargeCycleEntry

class BatteryChargeCycleEntryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatteryChargeCycleEntry
        //val modelInstance = BatteryChargeCycleEntry()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `batteryId`
        should("test batteryId") {
            // uncomment below to test the property
            //modelInstance.batteryId shouldBe ("TODO")
        }

        // to test the property `trackedTime`
        should("test trackedTime") {
            // uncomment below to test the property
            //modelInstance.trackedTime shouldBe ("TODO")
        }

        // to test the property `rowCreatedTimestamp`
        should("test rowCreatedTimestamp") {
            // uncomment below to test the property
            //modelInstance.rowCreatedTimestamp shouldBe ("TODO")
        }

    }
}
