/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BatteryDetailsResponse
import org.openapitools.client.models.Battery

class BatteryDetailsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatteryDetailsResponse
        //val modelInstance = BatteryDetailsResponse()

        // to test the property `chore`
        should("test chore") {
            // uncomment below to test the property
            //modelInstance.chore shouldBe ("TODO")
        }

        // to test the property `lastCharged` - When this battery was last charged
        should("test lastCharged") {
            // uncomment below to test the property
            //modelInstance.lastCharged shouldBe ("TODO")
        }

        // to test the property `chargeCyclesCount` - How often this battery was charged so far
        should("test chargeCyclesCount") {
            // uncomment below to test the property
            //modelInstance.chargeCyclesCount shouldBe ("TODO")
        }

        // to test the property `nextEstimatedChargeTime`
        should("test nextEstimatedChargeTime") {
            // uncomment below to test the property
            //modelInstance.nextEstimatedChargeTime shouldBe ("TODO")
        }

    }
}
