/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ChoreDetailsResponse
import org.openapitools.client.models.Chore
import org.openapitools.client.models.UserDto

class ChoreDetailsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChoreDetailsResponse
        //val modelInstance = ChoreDetailsResponse()

        // to test the property `chore`
        should("test chore") {
            // uncomment below to test the property
            //modelInstance.chore shouldBe ("TODO")
        }

        // to test the property `lastTracked` - When this chore was last tracked
        should("test lastTracked") {
            // uncomment below to test the property
            //modelInstance.lastTracked shouldBe ("TODO")
        }

        // to test the property `trackCount` - How often this chore was tracked so far
        should("test trackCount") {
            // uncomment below to test the property
            //modelInstance.trackCount shouldBe ("TODO")
        }

        // to test the property `lastDoneBy`
        should("test lastDoneBy") {
            // uncomment below to test the property
            //modelInstance.lastDoneBy shouldBe ("TODO")
        }

        // to test the property `nextEstimatedExecutionTime`
        should("test nextEstimatedExecutionTime") {
            // uncomment below to test the property
            //modelInstance.nextEstimatedExecutionTime shouldBe ("TODO")
        }

        // to test the property `nextExecutionAssignedUser`
        should("test nextExecutionAssignedUser") {
            // uncomment below to test the property
            //modelInstance.nextExecutionAssignedUser shouldBe ("TODO")
        }

        // to test the property `averageExecutionFrequencyHours` - Contains the average past execution frequency in hours or `null`, when the chore was never executed before
        should("test averageExecutionFrequencyHours") {
            // uncomment below to test the property
            //modelInstance.averageExecutionFrequencyHours shouldBe ("TODO")
        }

    }
}
