/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ChoresExecutionsCalculateNextAssignmentsPostRequest

class ChoresExecutionsCalculateNextAssignmentsPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChoresExecutionsCalculateNextAssignmentsPostRequest
        //val modelInstance = ChoresExecutionsCalculateNextAssignmentsPostRequest()

        // to test the property `choreId` - The chore id of the chore which next user assignment should be (re)calculated, when omitted, the next user assignments of all chores will (re)caluclated
        should("test choreId") {
            // uncomment below to test the property
            //modelInstance.choreId shouldBe ("TODO")
        }

    }
}
