/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ChoresChoreIdExecutePostRequest

class ChoresChoreIdExecutePostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChoresChoreIdExecutePostRequest
        //val modelInstance = ChoresChoreIdExecutePostRequest()

        // to test the property `trackedTime` - The time of when the chore was executed, when omitted, the current time is used
        should("test trackedTime") {
            // uncomment below to test the property
            //modelInstance.trackedTime shouldBe ("TODO")
        }

        // to test the property `doneBy` - A valid user id of who executed this chore, when omitted, the currently authenticated user will be used
        should("test doneBy") {
            // uncomment below to test the property
            //modelInstance.doneBy shouldBe ("TODO")
        }

        // to test the property `skipped` - `true` when the execution should be tracked as skipped, defaults to `false` when omitted
        should("test skipped") {
            // uncomment below to test the property
            //modelInstance.skipped shouldBe ("TODO")
        }

    }
}
