/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CurrentStockResponse
import org.openapitools.client.models.ProductWithoutUserfields

class CurrentStockResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrentStockResponse
        //val modelInstance = CurrentStockResponse()

        // to test the property `productId`
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `amountAggregated`
        should("test amountAggregated") {
            // uncomment below to test the property
            //modelInstance.amountAggregated shouldBe ("TODO")
        }

        // to test the property `amountOpened`
        should("test amountOpened") {
            // uncomment below to test the property
            //modelInstance.amountOpened shouldBe ("TODO")
        }

        // to test the property `amountOpenedAggregated`
        should("test amountOpenedAggregated") {
            // uncomment below to test the property
            //modelInstance.amountOpenedAggregated shouldBe ("TODO")
        }

        // to test the property `bestBeforeDate` - The next due date for this product
        should("test bestBeforeDate") {
            // uncomment below to test the property
            //modelInstance.bestBeforeDate shouldBe ("TODO")
        }

        // to test the property `isAggregatedAmount` - Indicates wheter this product has sub-products or not / if the fields `amount_aggregated` and `amount_opened_aggregated` are filled
        should("test isAggregatedAmount") {
            // uncomment below to test the property
            //modelInstance.isAggregatedAmount shouldBe ("TODO")
        }

        // to test the property `product`
        should("test product") {
            // uncomment below to test the property
            //modelInstance.product shouldBe ("TODO")
        }

    }
}
