/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CurrentBatteryResponse

class CurrentBatteryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrentBatteryResponse
        //val modelInstance = CurrentBatteryResponse()

        // to test the property `batteryId`
        should("test batteryId") {
            // uncomment below to test the property
            //modelInstance.batteryId shouldBe ("TODO")
        }

        // to test the property `lastTrackedTime`
        should("test lastTrackedTime") {
            // uncomment below to test the property
            //modelInstance.lastTrackedTime shouldBe ("TODO")
        }

        // to test the property `nextEstimatedChargeTime` - The next estimated charge time of this battery, 2999-12-31 23:59:59 when the given battery has no charge_interval_days defined
        should("test nextEstimatedChargeTime") {
            // uncomment below to test the property
            //modelInstance.nextEstimatedChargeTime shouldBe ("TODO")
        }

    }
}
