/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CurrentTaskResponse
import org.openapitools.client.models.TaskCategory
import org.openapitools.client.models.UserDto

class CurrentTaskResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrentTaskResponse
        //val modelInstance = CurrentTaskResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `dueDate`
        should("test dueDate") {
            // uncomment below to test the property
            //modelInstance.dueDate shouldBe ("TODO")
        }

        // to test the property `done`
        should("test done") {
            // uncomment below to test the property
            //modelInstance.done shouldBe ("TODO")
        }

        // to test the property `doneTimestamp`
        should("test doneTimestamp") {
            // uncomment below to test the property
            //modelInstance.doneTimestamp shouldBe ("TODO")
        }

        // to test the property `categoryId`
        should("test categoryId") {
            // uncomment below to test the property
            //modelInstance.categoryId shouldBe ("TODO")
        }

        // to test the property `assignedToUserId`
        should("test assignedToUserId") {
            // uncomment below to test the property
            //modelInstance.assignedToUserId shouldBe ("TODO")
        }

        // to test the property `rowCreatedTimestamp`
        should("test rowCreatedTimestamp") {
            // uncomment below to test the property
            //modelInstance.rowCreatedTimestamp shouldBe ("TODO")
        }

        // to test the property `assignedToUser`
        should("test assignedToUser") {
            // uncomment below to test the property
            //modelInstance.assignedToUser shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

    }
}
