/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CurrentChoreResponse
import org.openapitools.client.models.UserDto

class CurrentChoreResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrentChoreResponse
        //val modelInstance = CurrentChoreResponse()

        // to test the property `choreId`
        should("test choreId") {
            // uncomment below to test the property
            //modelInstance.choreId shouldBe ("TODO")
        }

        // to test the property `choreName`
        should("test choreName") {
            // uncomment below to test the property
            //modelInstance.choreName shouldBe ("TODO")
        }

        // to test the property `lastTrackedTime`
        should("test lastTrackedTime") {
            // uncomment below to test the property
            //modelInstance.lastTrackedTime shouldBe ("TODO")
        }

        // to test the property `trackDateOnly`
        should("test trackDateOnly") {
            // uncomment below to test the property
            //modelInstance.trackDateOnly shouldBe ("TODO")
        }

        // to test the property `nextEstimatedExecutionTime` - The next estimated execution time of this chore, 2999-12-31 23:59:59 when the given chore has a period_type of manually
        should("test nextEstimatedExecutionTime") {
            // uncomment below to test the property
            //modelInstance.nextEstimatedExecutionTime shouldBe ("TODO")
        }

        // to test the property `nextExecutionAssignedToUserId`
        should("test nextExecutionAssignedToUserId") {
            // uncomment below to test the property
            //modelInstance.nextExecutionAssignedToUserId shouldBe ("TODO")
        }

        // to test the property `isRescheduled`
        should("test isRescheduled") {
            // uncomment below to test the property
            //modelInstance.isRescheduled shouldBe ("TODO")
        }

        // to test the property `isReassigned`
        should("test isReassigned") {
            // uncomment below to test the property
            //modelInstance.isReassigned shouldBe ("TODO")
        }

        // to test the property `nextExecutionAssignedUser`
        should("test nextExecutionAssignedUser") {
            // uncomment below to test the property
            //modelInstance.nextExecutionAssignedUser shouldBe ("TODO")
        }

    }
}
