/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CurrentVolatilStockResponse
import org.openapitools.client.models.CurrentStockResponse
import org.openapitools.client.models.CurrentVolatilStockResponseMissingProductsInner

class CurrentVolatilStockResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CurrentVolatilStockResponse
        //val modelInstance = CurrentVolatilStockResponse()

        // to test the property `dueProducts`
        should("test dueProducts") {
            // uncomment below to test the property
            //modelInstance.dueProducts shouldBe ("TODO")
        }

        // to test the property `overdueProducts`
        should("test overdueProducts") {
            // uncomment below to test the property
            //modelInstance.overdueProducts shouldBe ("TODO")
        }

        // to test the property `expiredProducts`
        should("test expiredProducts") {
            // uncomment below to test the property
            //modelInstance.expiredProducts shouldBe ("TODO")
        }

        // to test the property `missingProducts`
        should("test missingProducts") {
            // uncomment below to test the property
            //modelInstance.missingProducts shouldBe ("TODO")
        }

    }
}
