/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Error500
import org.openapitools.client.models.Error500ErrorDetails

class Error500Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of Error500
        //val modelInstance = Error500()

        // to test the property `errorMessage`
        should("test errorMessage") {
            // uncomment below to test the property
            //modelInstance.errorMessage shouldBe ("TODO")
        }

        // to test the property `errorDetails`
        should("test errorDetails") {
            // uncomment below to test the property
            //modelInstance.errorDetails shouldBe ("TODO")
        }

    }
}
