/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Error500ErrorDetails

class Error500ErrorDetailsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Error500ErrorDetails
        //val modelInstance = Error500ErrorDetails()

        // to test the property `stackTrace`
        should("test stackTrace") {
            // uncomment below to test the property
            //modelInstance.stackTrace shouldBe ("TODO")
        }

        // to test the property `file`
        should("test file") {
            // uncomment below to test the property
            //modelInstance.file shouldBe ("TODO")
        }

        // to test the property `line`
        should("test line") {
            // uncomment below to test the property
            //modelInstance.line shouldBe ("TODO")
        }

    }
}
