/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExternalBarcodeLookupResponse

class ExternalBarcodeLookupResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExternalBarcodeLookupResponse
        //val modelInstance = ExternalBarcodeLookupResponse()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `locationId`
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `quIdPurchase`
        should("test quIdPurchase") {
            // uncomment below to test the property
            //modelInstance.quIdPurchase shouldBe ("TODO")
        }

        // to test the property `quIdStock`
        should("test quIdStock") {
            // uncomment below to test the property
            //modelInstance.quIdStock shouldBe ("TODO")
        }

        // to test the property `quFactorPurchaseToStock`
        should("test quFactorPurchaseToStock") {
            // uncomment below to test the property
            //modelInstance.quFactorPurchaseToStock shouldBe ("TODO")
        }

        // to test the property `barcode` - Can contain multiple barcodes separated by comma
        should("test barcode") {
            // uncomment below to test the property
            //modelInstance.barcode shouldBe ("TODO")
        }

        // to test the property `id` - The id of the added product, only included when the producted was added to the database
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
