/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ObjectsEntityGet200ResponseInner
import org.openapitools.client.models.Battery
import org.openapitools.client.models.Chore
import org.openapitools.client.models.Location
import org.openapitools.client.models.Product
import org.openapitools.client.models.ProductBarcode
import org.openapitools.client.models.QuantityUnit
import org.openapitools.client.models.ShoppingListItem
import org.openapitools.client.models.StockEntry

class ObjectsEntityGet200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ObjectsEntityGet200ResponseInner
        //val modelInstance = ObjectsEntityGet200ResponseInner()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `locationId`
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `quIdPurchase`
        should("test quIdPurchase") {
            // uncomment below to test the property
            //modelInstance.quIdPurchase shouldBe ("TODO")
        }

        // to test the property `quIdStock`
        should("test quIdStock") {
            // uncomment below to test the property
            //modelInstance.quIdStock shouldBe ("TODO")
        }

        // to test the property `enableTareWeightHandling`
        should("test enableTareWeightHandling") {
            // uncomment below to test the property
            //modelInstance.enableTareWeightHandling shouldBe ("TODO")
        }

        // to test the property `notCheckStockFulfillmentForRecipes`
        should("test notCheckStockFulfillmentForRecipes") {
            // uncomment below to test the property
            //modelInstance.notCheckStockFulfillmentForRecipes shouldBe ("TODO")
        }

        // to test the property `productGroupId`
        should("test productGroupId") {
            // uncomment below to test the property
            //modelInstance.productGroupId shouldBe ("TODO")
        }

        // to test the property `tareWeight`
        should("test tareWeight") {
            // uncomment below to test the property
            //modelInstance.tareWeight shouldBe ("TODO")
        }

        // to test the property `minStockAmount`
        should("test minStockAmount") {
            // uncomment below to test the property
            //modelInstance.minStockAmount shouldBe ("TODO")
        }

        // to test the property `defaultBestBeforeDays`
        should("test defaultBestBeforeDays") {
            // uncomment below to test the property
            //modelInstance.defaultBestBeforeDays shouldBe ("TODO")
        }

        // to test the property `defaultBestBeforeDaysAfterOpen`
        should("test defaultBestBeforeDaysAfterOpen") {
            // uncomment below to test the property
            //modelInstance.defaultBestBeforeDaysAfterOpen shouldBe ("TODO")
        }

        // to test the property `pictureFileName`
        should("test pictureFileName") {
            // uncomment below to test the property
            //modelInstance.pictureFileName shouldBe ("TODO")
        }

        // to test the property `rowCreatedTimestamp`
        should("test rowCreatedTimestamp") {
            // uncomment below to test the property
            //modelInstance.rowCreatedTimestamp shouldBe ("TODO")
        }

        // to test the property `shoppingLocationId`
        should("test shoppingLocationId") {
            // uncomment below to test the property
            //modelInstance.shoppingLocationId shouldBe ("TODO")
        }

        // to test the property `treatOpenedAsOutOfStock`
        should("test treatOpenedAsOutOfStock") {
            // uncomment below to test the property
            //modelInstance.treatOpenedAsOutOfStock shouldBe ("TODO")
        }

        // to test the property `autoReprintStockLabel`
        should("test autoReprintStockLabel") {
            // uncomment below to test the property
            //modelInstance.autoReprintStockLabel shouldBe ("TODO")
        }

        // to test the property `noOwnStock`
        should("test noOwnStock") {
            // uncomment below to test the property
            //modelInstance.noOwnStock shouldBe ("TODO")
        }

        // to test the property `userfields` - Key/value pairs of userfields
        should("test userfields") {
            // uncomment below to test the property
            //modelInstance.userfields shouldBe ("TODO")
        }

        // to test the property `shouldNotBeFrozen`
        should("test shouldNotBeFrozen") {
            // uncomment below to test the property
            //modelInstance.shouldNotBeFrozen shouldBe ("TODO")
        }

        // to test the property `defaultConsumeLocationId`
        should("test defaultConsumeLocationId") {
            // uncomment below to test the property
            //modelInstance.defaultConsumeLocationId shouldBe ("TODO")
        }

        // to test the property `moveOnOpen`
        should("test moveOnOpen") {
            // uncomment below to test the property
            //modelInstance.moveOnOpen shouldBe ("TODO")
        }

        // to test the property `periodType`
        should("test periodType") {
            // uncomment below to test the property
            //modelInstance.periodType shouldBe ("TODO")
        }

        // to test the property `periodConfig`
        should("test periodConfig") {
            // uncomment below to test the property
            //modelInstance.periodConfig shouldBe ("TODO")
        }

        // to test the property `periodDays`
        should("test periodDays") {
            // uncomment below to test the property
            //modelInstance.periodDays shouldBe ("TODO")
        }

        // to test the property `trackDateOnly`
        should("test trackDateOnly") {
            // uncomment below to test the property
            //modelInstance.trackDateOnly shouldBe ("TODO")
        }

        // to test the property `rollover`
        should("test rollover") {
            // uncomment below to test the property
            //modelInstance.rollover shouldBe ("TODO")
        }

        // to test the property `assignmentType`
        should("test assignmentType") {
            // uncomment below to test the property
            //modelInstance.assignmentType shouldBe ("TODO")
        }

        // to test the property `assignmentConfig`
        should("test assignmentConfig") {
            // uncomment below to test the property
            //modelInstance.assignmentConfig shouldBe ("TODO")
        }

        // to test the property `nextExecutionAssignedToUserId`
        should("test nextExecutionAssignedToUserId") {
            // uncomment below to test the property
            //modelInstance.nextExecutionAssignedToUserId shouldBe ("TODO")
        }

        // to test the property `startDate`
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

        // to test the property `rescheduledDate`
        should("test rescheduledDate") {
            // uncomment below to test the property
            //modelInstance.rescheduledDate shouldBe ("TODO")
        }

        // to test the property `rescheduledNextExecutionAssignedToUserId`
        should("test rescheduledNextExecutionAssignedToUserId") {
            // uncomment below to test the property
            //modelInstance.rescheduledNextExecutionAssignedToUserId shouldBe ("TODO")
        }

        // to test the property `usedIn`
        should("test usedIn") {
            // uncomment below to test the property
            //modelInstance.usedIn shouldBe ("TODO")
        }

        // to test the property `chargeIntervalDays`
        should("test chargeIntervalDays") {
            // uncomment below to test the property
            //modelInstance.chargeIntervalDays shouldBe ("TODO")
        }

        // to test the property `namePlural`
        should("test namePlural") {
            // uncomment below to test the property
            //modelInstance.namePlural shouldBe ("TODO")
        }

        // to test the property `pluralForms`
        should("test pluralForms") {
            // uncomment below to test the property
            //modelInstance.pluralForms shouldBe ("TODO")
        }

        // to test the property `shoppingListId`
        should("test shoppingListId") {
            // uncomment below to test the property
            //modelInstance.shoppingListId shouldBe ("TODO")
        }

        // to test the property `productId`
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `bestBeforeDate`
        should("test bestBeforeDate") {
            // uncomment below to test the property
            //modelInstance.bestBeforeDate shouldBe ("TODO")
        }

        // to test the property `purchasedDate`
        should("test purchasedDate") {
            // uncomment below to test the property
            //modelInstance.purchasedDate shouldBe ("TODO")
        }

        // to test the property `stockId` - A unique id which references this stock entry during its lifetime
        should("test stockId") {
            // uncomment below to test the property
            //modelInstance.stockId shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property ``open``
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

        // to test the property `openedDate`
        should("test openedDate") {
            // uncomment below to test the property
            //modelInstance.openedDate shouldBe ("TODO")
        }

        // to test the property `barcode`
        should("test barcode") {
            // uncomment below to test the property
            //modelInstance.barcode shouldBe ("TODO")
        }

        // to test the property `quId`
        should("test quId") {
            // uncomment below to test the property
            //modelInstance.quId shouldBe ("TODO")
        }

        // to test the property `lastPrice`
        should("test lastPrice") {
            // uncomment below to test the property
            //modelInstance.lastPrice shouldBe ("TODO")
        }

    }
}
