/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Product

class ProductTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Product
        //val modelInstance = Product()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `locationId`
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `quIdPurchase`
        should("test quIdPurchase") {
            // uncomment below to test the property
            //modelInstance.quIdPurchase shouldBe ("TODO")
        }

        // to test the property `quIdStock`
        should("test quIdStock") {
            // uncomment below to test the property
            //modelInstance.quIdStock shouldBe ("TODO")
        }

        // to test the property `enableTareWeightHandling`
        should("test enableTareWeightHandling") {
            // uncomment below to test the property
            //modelInstance.enableTareWeightHandling shouldBe ("TODO")
        }

        // to test the property `notCheckStockFulfillmentForRecipes`
        should("test notCheckStockFulfillmentForRecipes") {
            // uncomment below to test the property
            //modelInstance.notCheckStockFulfillmentForRecipes shouldBe ("TODO")
        }

        // to test the property `productGroupId`
        should("test productGroupId") {
            // uncomment below to test the property
            //modelInstance.productGroupId shouldBe ("TODO")
        }

        // to test the property `tareWeight`
        should("test tareWeight") {
            // uncomment below to test the property
            //modelInstance.tareWeight shouldBe ("TODO")
        }

        // to test the property `minStockAmount`
        should("test minStockAmount") {
            // uncomment below to test the property
            //modelInstance.minStockAmount shouldBe ("TODO")
        }

        // to test the property `defaultBestBeforeDays`
        should("test defaultBestBeforeDays") {
            // uncomment below to test the property
            //modelInstance.defaultBestBeforeDays shouldBe ("TODO")
        }

        // to test the property `defaultBestBeforeDaysAfterOpen`
        should("test defaultBestBeforeDaysAfterOpen") {
            // uncomment below to test the property
            //modelInstance.defaultBestBeforeDaysAfterOpen shouldBe ("TODO")
        }

        // to test the property `pictureFileName`
        should("test pictureFileName") {
            // uncomment below to test the property
            //modelInstance.pictureFileName shouldBe ("TODO")
        }

        // to test the property `rowCreatedTimestamp`
        should("test rowCreatedTimestamp") {
            // uncomment below to test the property
            //modelInstance.rowCreatedTimestamp shouldBe ("TODO")
        }

        // to test the property `shoppingLocationId`
        should("test shoppingLocationId") {
            // uncomment below to test the property
            //modelInstance.shoppingLocationId shouldBe ("TODO")
        }

        // to test the property `treatOpenedAsOutOfStock`
        should("test treatOpenedAsOutOfStock") {
            // uncomment below to test the property
            //modelInstance.treatOpenedAsOutOfStock shouldBe ("TODO")
        }

        // to test the property `autoReprintStockLabel`
        should("test autoReprintStockLabel") {
            // uncomment below to test the property
            //modelInstance.autoReprintStockLabel shouldBe ("TODO")
        }

        // to test the property `noOwnStock`
        should("test noOwnStock") {
            // uncomment below to test the property
            //modelInstance.noOwnStock shouldBe ("TODO")
        }

        // to test the property `userfields` - Key/value pairs of userfields
        should("test userfields") {
            // uncomment below to test the property
            //modelInstance.userfields shouldBe ("TODO")
        }

        // to test the property `shouldNotBeFrozen`
        should("test shouldNotBeFrozen") {
            // uncomment below to test the property
            //modelInstance.shouldNotBeFrozen shouldBe ("TODO")
        }

        // to test the property `defaultConsumeLocationId`
        should("test defaultConsumeLocationId") {
            // uncomment below to test the property
            //modelInstance.defaultConsumeLocationId shouldBe ("TODO")
        }

        // to test the property `moveOnOpen`
        should("test moveOnOpen") {
            // uncomment below to test the property
            //modelInstance.moveOnOpen shouldBe ("TODO")
        }

    }
}
