/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductDetailsResponse
import org.openapitools.client.models.Location
import org.openapitools.client.models.Product
import org.openapitools.client.models.ProductBarcode
import org.openapitools.client.models.QuantityUnit

class ProductDetailsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductDetailsResponse
        //val modelInstance = ProductDetailsResponse()

        // to test the property `product`
        should("test product") {
            // uncomment below to test the property
            //modelInstance.product shouldBe ("TODO")
        }

        // to test the property `productBarcodes`
        should("test productBarcodes") {
            // uncomment below to test the property
            //modelInstance.productBarcodes shouldBe ("TODO")
        }

        // to test the property `quantityUnitStock`
        should("test quantityUnitStock") {
            // uncomment below to test the property
            //modelInstance.quantityUnitStock shouldBe ("TODO")
        }

        // to test the property `defaultQuantityUnitPurchase`
        should("test defaultQuantityUnitPurchase") {
            // uncomment below to test the property
            //modelInstance.defaultQuantityUnitPurchase shouldBe ("TODO")
        }

        // to test the property `defaultQuantityUnitConsume`
        should("test defaultQuantityUnitConsume") {
            // uncomment below to test the property
            //modelInstance.defaultQuantityUnitConsume shouldBe ("TODO")
        }

        // to test the property `quantityUnitPrice`
        should("test quantityUnitPrice") {
            // uncomment below to test the property
            //modelInstance.quantityUnitPrice shouldBe ("TODO")
        }

        // to test the property `lastPurchased`
        should("test lastPurchased") {
            // uncomment below to test the property
            //modelInstance.lastPurchased shouldBe ("TODO")
        }

        // to test the property `lastUsed`
        should("test lastUsed") {
            // uncomment below to test the property
            //modelInstance.lastUsed shouldBe ("TODO")
        }

        // to test the property `stockAmount`
        should("test stockAmount") {
            // uncomment below to test the property
            //modelInstance.stockAmount shouldBe ("TODO")
        }

        // to test the property `stockAmountOpened`
        should("test stockAmountOpened") {
            // uncomment below to test the property
            //modelInstance.stockAmountOpened shouldBe ("TODO")
        }

        // to test the property `nextDueDate`
        should("test nextDueDate") {
            // uncomment below to test the property
            //modelInstance.nextDueDate shouldBe ("TODO")
        }

        // to test the property `lastPrice` - The price of the last purchase of the corresponding product
        should("test lastPrice") {
            // uncomment below to test the property
            //modelInstance.lastPrice shouldBe ("TODO")
        }

        // to test the property `avgPrice` - The average price af all stock entries currently in stock of the corresponding product
        should("test avgPrice") {
            // uncomment below to test the property
            //modelInstance.avgPrice shouldBe ("TODO")
        }

        // to test the property `currentPrice` - The current price of the corresponding product, based on the stock entry to use next (defined by the default consume rule \"Opened first, then first due first, then first in first out\") or on the last price if the product is currently not in stock
        should("test currentPrice") {
            // uncomment below to test the property
            //modelInstance.currentPrice shouldBe ("TODO")
        }

        // to test the property `oldestPrice` - This field is deprecated and will be removed in a future version (currently returns the same as `current_price`)
        should("test oldestPrice") {
            // uncomment below to test the property
            //modelInstance.oldestPrice shouldBe ("TODO")
        }

        // to test the property `lastShoppingLocationId`
        should("test lastShoppingLocationId") {
            // uncomment below to test the property
            //modelInstance.lastShoppingLocationId shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `averageShelfLifeDays`
        should("test averageShelfLifeDays") {
            // uncomment below to test the property
            //modelInstance.averageShelfLifeDays shouldBe ("TODO")
        }

        // to test the property `spoilRatePercent`
        should("test spoilRatePercent") {
            // uncomment below to test the property
            //modelInstance.spoilRatePercent shouldBe ("TODO")
        }

        // to test the property `hasChilds` - True when the product is a parent product of others
        should("test hasChilds") {
            // uncomment below to test the property
            //modelInstance.hasChilds shouldBe ("TODO")
        }

        // to test the property `defaultLocation`
        should("test defaultLocation") {
            // uncomment below to test the property
            //modelInstance.defaultLocation shouldBe ("TODO")
        }

        // to test the property `quConversionFactorPurchaseToStock` - The conversion factor of the corresponding QU conversion from the product's qu_id_purchase to qu_id_stock
        should("test quConversionFactorPurchaseToStock") {
            // uncomment below to test the property
            //modelInstance.quConversionFactorPurchaseToStock shouldBe ("TODO")
        }

        // to test the property `quConversionFactorPriceToStock` - The conversion factor of the corresponding QU conversion from the product's qu_id_price to qu_id_stock
        should("test quConversionFactorPriceToStock") {
            // uncomment below to test the property
            //modelInstance.quConversionFactorPriceToStock shouldBe ("TODO")
        }

    }
}
