/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RecipesRecipeIdCopyPost200Response

class RecipesRecipeIdCopyPost200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecipesRecipeIdCopyPost200Response
        //val modelInstance = RecipesRecipeIdCopyPost200Response()

        // to test the property `createdObjectId` - The id of the created recipe
        should("test createdObjectId") {
            // uncomment below to test the property
            //modelInstance.createdObjectId shouldBe ("TODO")
        }

    }
}
