/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockJournalSummary
import org.openapitools.client.models.StockTransactionType

class StockJournalSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockJournalSummary
        //val modelInstance = StockJournalSummary()

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `productName`
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `productId`
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `quName`
        should("test quName") {
            // uncomment below to test the property
            //modelInstance.quName shouldBe ("TODO")
        }

        // to test the property `quNamePlural`
        should("test quNamePlural") {
            // uncomment below to test the property
            //modelInstance.quNamePlural shouldBe ("TODO")
        }

        // to test the property `userDisplayName`
        should("test userDisplayName") {
            // uncomment below to test the property
            //modelInstance.userDisplayName shouldBe ("TODO")
        }

        // to test the property `transactionType`
        should("test transactionType") {
            // uncomment below to test the property
            //modelInstance.transactionType shouldBe ("TODO")
        }

    }
}
