/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockProductsProductIdTransferPostRequest

class StockProductsProductIdTransferPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockProductsProductIdTransferPostRequest
        //val modelInstance = StockProductsProductIdTransferPostRequest()

        // to test the property `amount` - The amount to transfer - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `locationIdFrom` - A valid location id, the location from where the product should be transfered
        should("test locationIdFrom") {
            // uncomment below to test the property
            //modelInstance.locationIdFrom shouldBe ("TODO")
        }

        // to test the property `locationIdTo` - A valid location id, the location to where the product should be transfered
        should("test locationIdTo") {
            // uncomment below to test the property
            //modelInstance.locationIdTo shouldBe ("TODO")
        }

        // to test the property `stockEntryId` - A specific stock entry id to transfer, if used, the amount has to be 1
        should("test stockEntryId") {
            // uncomment below to test the property
            //modelInstance.stockEntryId shouldBe ("TODO")
        }

    }
}
