/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockJournal
import org.openapitools.client.models.StockTransactionType

class StockJournalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockJournal
        //val modelInstance = StockJournal()

        // to test the property `correlationId`
        should("test correlationId") {
            // uncomment below to test the property
            //modelInstance.correlationId shouldBe ("TODO")
        }

        // to test the property `undone`
        should("test undone") {
            // uncomment below to test the property
            //modelInstance.undone shouldBe ("TODO")
        }

        // to test the property `undoneTimestamp`
        should("test undoneTimestamp") {
            // uncomment below to test the property
            //modelInstance.undoneTimestamp shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `locationId`
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `locationName`
        should("test locationName") {
            // uncomment below to test the property
            //modelInstance.locationName shouldBe ("TODO")
        }

        // to test the property `productName`
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `quName`
        should("test quName") {
            // uncomment below to test the property
            //modelInstance.quName shouldBe ("TODO")
        }

        // to test the property `quNamePlural`
        should("test quNamePlural") {
            // uncomment below to test the property
            //modelInstance.quNamePlural shouldBe ("TODO")
        }

        // to test the property `userDisplayName`
        should("test userDisplayName") {
            // uncomment below to test the property
            //modelInstance.userDisplayName shouldBe ("TODO")
        }

        // to test the property `spoiled`
        should("test spoiled") {
            // uncomment below to test the property
            //modelInstance.spoiled shouldBe ("TODO")
        }

        // to test the property `transactionType`
        should("test transactionType") {
            // uncomment below to test the property
            //modelInstance.transactionType shouldBe ("TODO")
        }

        // to test the property `rowCreatedTimestamp`
        should("test rowCreatedTimestamp") {
            // uncomment below to test the property
            //modelInstance.rowCreatedTimestamp shouldBe ("TODO")
        }

    }
}
