/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockProductsProductIdInventoryPostRequest

class StockProductsProductIdInventoryPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockProductsProductIdInventoryPostRequest
        //val modelInstance = StockProductsProductIdInventoryPostRequest()

        // to test the property `newAmount` - The new current amount for the given product - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
        should("test newAmount") {
            // uncomment below to test the property
            //modelInstance.newAmount shouldBe ("TODO")
        }

        // to test the property `bestBeforeDate` - The due date which applies to added products
        should("test bestBeforeDate") {
            // uncomment below to test the property
            //modelInstance.bestBeforeDate shouldBe ("TODO")
        }

        // to test the property `shoppingLocationId` - If omitted, no store will be affected
        should("test shoppingLocationId") {
            // uncomment below to test the property
            //modelInstance.shoppingLocationId shouldBe ("TODO")
        }

        // to test the property `locationId` - If omitted, the default location of the product is used (only applies to added products)
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `price` - If omitted, the last price of the product is used (only applies to added products)
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `stockLabelType` - `1` = No label, `2` = Single label, `3` = Label per unit (only applies to added products)
        should("test stockLabelType") {
            // uncomment below to test the property
            //modelInstance.stockLabelType shouldBe ("TODO")
        }

        // to test the property `note` - An optional note for the corresponding stock entry (only applies to added products)
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
