/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockProductsProductIdAddPostRequest
import org.openapitools.client.models.StockTransactionType

class StockProductsProductIdAddPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockProductsProductIdAddPostRequest
        //val modelInstance = StockProductsProductIdAddPostRequest()

        // to test the property `amount` - The amount to add - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `bestBeforeDate` - The due date of the product to add, when omitted, the current date is used
        should("test bestBeforeDate") {
            // uncomment below to test the property
            //modelInstance.bestBeforeDate shouldBe ("TODO")
        }

        // to test the property `transactionType`
        should("test transactionType") {
            // uncomment below to test the property
            //modelInstance.transactionType shouldBe ("TODO")
        }

        // to test the property `price` - The price per stock quantity unit in configured currency
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `locationId` - If omitted, the default location of the product is used
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `shoppingLocationId` - If omitted, no store will be affected
        should("test shoppingLocationId") {
            // uncomment below to test the property
            //modelInstance.shoppingLocationId shouldBe ("TODO")
        }

        // to test the property `stockLabelType` - `1` = No label, `2` = Single label, `3` = Label per unit
        should("test stockLabelType") {
            // uncomment below to test the property
            //modelInstance.stockLabelType shouldBe ("TODO")
        }

        // to test the property `note` - An optional note for the corresponding stock entry
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
