/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockShoppinglistAddProductPostRequest

class StockShoppinglistAddProductPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockShoppinglistAddProductPostRequest
        //val modelInstance = StockShoppinglistAddProductPostRequest()

        // to test the property `productId` - A valid product id of the product to be added
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `quId` - A valid quantity unit id (used only for display; the amount needs to be related to the products stock QU), when omitted, the products stock QU is used
        should("test quId") {
            // uncomment below to test the property
            //modelInstance.quId shouldBe ("TODO")
        }

        // to test the property `listId` - A valid shopping list id, when omitted, the default shopping list (with id 1) is used
        should("test listId") {
            // uncomment below to test the property
            //modelInstance.listId shouldBe ("TODO")
        }

        // to test the property `productAmount` - The amount (related to the products stock QU) to add, when omitted, the default amount of 1 is used
        should("test productAmount") {
            // uncomment below to test the property
            //modelInstance.productAmount shouldBe ("TODO")
        }

        // to test the property `note` - The note of the shopping list item
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

    }
}
