/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockShoppinglistClearPostRequest

class StockShoppinglistClearPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockShoppinglistClearPostRequest
        //val modelInstance = StockShoppinglistClearPostRequest()

        // to test the property `listId` - The shopping list id to clear, when omitted, the default shopping list (with id 1) is used
        should("test listId") {
            // uncomment below to test the property
            //modelInstance.listId shouldBe ("TODO")
        }

        // to test the property `doneOnly` - When `true`, only done items will be removed (defaults to `false` when ommited)
        should("test doneOnly") {
            // uncomment below to test the property
            //modelInstance.doneOnly shouldBe ("TODO")
        }

    }
}
