/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StockProductsByBarcodeBarcodeConsumePostRequest
import org.openapitools.client.models.StockTransactionType

class StockProductsByBarcodeBarcodeConsumePostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockProductsByBarcodeBarcodeConsumePostRequest
        //val modelInstance = StockProductsByBarcodeBarcodeConsumePostRequest()

        // to test the property `amount` - The amount to remove - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `transactionType`
        should("test transactionType") {
            // uncomment below to test the property
            //modelInstance.transactionType shouldBe ("TODO")
        }

        // to test the property `spoiled` - True when the given product was spoiled, defaults to false
        should("test spoiled") {
            // uncomment below to test the property
            //modelInstance.spoiled shouldBe ("TODO")
        }

        // to test the property `stockEntryId` - A specific stock entry id to consume, if used, the amount has to be 1
        should("test stockEntryId") {
            // uncomment below to test the property
            //modelInstance.stockEntryId shouldBe ("TODO")
        }

        // to test the property `recipeId` - A valid recipe id for which this product was used (for statistical purposes only)
        should("test recipeId") {
            // uncomment below to test the property
            //modelInstance.recipeId shouldBe ("TODO")
        }

        // to test the property `locationId` - A valid location id (if supplied, only stock at the given location is considered, if ommitted, stock of any location is considered)
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `exactAmount` - For tare weight handling enabled products, `true` when the given is the absolute amount to be consumed, not the amount including the container weight
        should("test exactAmount") {
            // uncomment below to test the property
            //modelInstance.exactAmount shouldBe ("TODO")
        }

        // to test the property `allowSubproductSubstitution` - `rue` when any in stock sub product should be used when the given product is a parent product and currently not in stock
        should("test allowSubproductSubstitution") {
            // uncomment below to test the property
            //modelInstance.allowSubproductSubstitution shouldBe ("TODO")
        }

    }
}
