/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SystemInfoGet200ResponseGrocyVersion

class SystemInfoGet200ResponseGrocyVersionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemInfoGet200ResponseGrocyVersion
        //val modelInstance = SystemInfoGet200ResponseGrocyVersion()

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `releaseDate`
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

    }
}
