/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SystemInfoGet200Response
import org.openapitools.client.models.SystemInfoGet200ResponseGrocyVersion

class SystemInfoGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemInfoGet200Response
        //val modelInstance = SystemInfoGet200Response()

        // to test the property `grocyVersion`
        should("test grocyVersion") {
            // uncomment below to test the property
            //modelInstance.grocyVersion shouldBe ("TODO")
        }

        // to test the property `phpVersion`
        should("test phpVersion") {
            // uncomment below to test the property
            //modelInstance.phpVersion shouldBe ("TODO")
        }

        // to test the property `sqliteVersion`
        should("test sqliteVersion") {
            // uncomment below to test the property
            //modelInstance.sqliteVersion shouldBe ("TODO")
        }

    }
}
