/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TimeResponse

class TimeResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimeResponse
        //val modelInstance = TimeResponse()

        // to test the property `timezone`
        should("test timezone") {
            // uncomment below to test the property
            //modelInstance.timezone shouldBe ("TODO")
        }

        // to test the property `timeLocal`
        should("test timeLocal") {
            // uncomment below to test the property
            //modelInstance.timeLocal shouldBe ("TODO")
        }

        // to test the property `timeLocalSqlite3`
        should("test timeLocalSqlite3") {
            // uncomment below to test the property
            //modelInstance.timeLocalSqlite3 shouldBe ("TODO")
        }

        // to test the property `timeUtc`
        should("test timeUtc") {
            // uncomment below to test the property
            //modelInstance.timeUtc shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `offset`
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

    }
}
