/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UsersUserIdPermissionsGet200ResponseInner

class UsersUserIdPermissionsGet200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersUserIdPermissionsGet200ResponseInner
        //val modelInstance = UsersUserIdPermissionsGet200ResponseInner()

        // to test the property `permissionId`
        should("test permissionId") {
            // uncomment below to test the property
            //modelInstance.permissionId shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
