/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.UsersUserIdPermissionsPostRequest

class UsersUserIdPermissionsPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersUserIdPermissionsPostRequest
        //val modelInstance = UsersUserIdPermissionsPostRequest()

        // to test the property `permissionsId` - A permission ids
        should("test permissionsId") {
            // uncomment below to test the property
            //modelInstance.permissionsId shouldBe ("TODO")
        }

    }
}
