/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.BatteriesApi
import org.openapitools.client.models.BatteriesBatteryIdChargePostRequest
import org.openapitools.client.models.BatteryChargeCycleEntry
import org.openapitools.client.models.BatteryDetailsResponse
import org.openapitools.client.models.CurrentBatteryResponse
import org.openapitools.client.models.Error400
import org.openapitools.client.models.Error500

class BatteriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatteriesApi
        //val apiInstance = BatteriesApi()

        // to test batteriesBatteryIdChargePost
        should("test batteriesBatteryIdChargePost") {
            // uncomment below to test batteriesBatteryIdChargePost
            //val batteryId : kotlin.Int = 56 // kotlin.Int | A valid battery id
            //val batteriesBatteryIdChargePostRequest : BatteriesBatteryIdChargePostRequest =  // BatteriesBatteryIdChargePostRequest | 
            //val result : BatteryChargeCycleEntry = apiInstance.batteriesBatteryIdChargePost(batteryId, batteriesBatteryIdChargePostRequest)
            //result shouldBe ("TODO")
        }

        // to test batteriesBatteryIdGet
        should("test batteriesBatteryIdGet") {
            // uncomment below to test batteriesBatteryIdGet
            //val batteryId : kotlin.Int = 56 // kotlin.Int | A valid battery id
            //val result : BatteryDetailsResponse = apiInstance.batteriesBatteryIdGet(batteryId)
            //result shouldBe ("TODO")
        }

        // to test batteriesBatteryIdPrintlabelGet
        should("test batteriesBatteryIdPrintlabelGet") {
            // uncomment below to test batteriesBatteryIdPrintlabelGet
            //val batteryId : kotlin.Int = 56 // kotlin.Int | A valid battery id
            //val result : kotlin.String = apiInstance.batteriesBatteryIdPrintlabelGet(batteryId)
            //result shouldBe ("TODO")
        }

        // to test batteriesChargeCyclesChargeCycleIdUndoPost
        should("test batteriesChargeCyclesChargeCycleIdUndoPost") {
            // uncomment below to test batteriesChargeCyclesChargeCycleIdUndoPost
            //val chargeCycleId : kotlin.Int = 56 // kotlin.Int | A valid charge cycle id
            //apiInstance.batteriesChargeCyclesChargeCycleIdUndoPost(chargeCycleId)
        }

        // to test batteriesGet
        should("test batteriesGet") {
            // uncomment below to test batteriesGet
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<CurrentBatteryResponse> = apiInstance.batteriesGet(query, order, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
