/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.CalendarApi
import org.openapitools.client.models.CalendarIcalSharingLinkGet200Response
import org.openapitools.client.models.Error400

class CalendarApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CalendarApi
        //val apiInstance = CalendarApi()

        // to test calendarIcalGet
        should("test calendarIcalGet") {
            // uncomment below to test calendarIcalGet
            //val result : kotlin.String = apiInstance.calendarIcalGet()
            //result shouldBe ("TODO")
        }

        // to test calendarIcalSharingLinkGet
        should("test calendarIcalSharingLinkGet") {
            // uncomment below to test calendarIcalSharingLinkGet
            //val result : CalendarIcalSharingLinkGet200Response = apiInstance.calendarIcalSharingLinkGet()
            //result shouldBe ("TODO")
        }

    }
}
