/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ChoresApi
import org.openapitools.client.models.ChoreDetailsResponse
import org.openapitools.client.models.ChoreLogEntry
import org.openapitools.client.models.ChoresChoreIdExecutePostRequest
import org.openapitools.client.models.ChoresExecutionsCalculateNextAssignmentsPostRequest
import org.openapitools.client.models.CurrentChoreResponse
import org.openapitools.client.models.Error400
import org.openapitools.client.models.Error500

class ChoresApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChoresApi
        //val apiInstance = ChoresApi()

        // to test choresChoreIdExecutePost
        should("test choresChoreIdExecutePost") {
            // uncomment below to test choresChoreIdExecutePost
            //val choreId : kotlin.Int = 56 // kotlin.Int | A valid chore id
            //val choresChoreIdExecutePostRequest : ChoresChoreIdExecutePostRequest =  // ChoresChoreIdExecutePostRequest | 
            //val result : ChoreLogEntry = apiInstance.choresChoreIdExecutePost(choreId, choresChoreIdExecutePostRequest)
            //result shouldBe ("TODO")
        }

        // to test choresChoreIdGet
        should("test choresChoreIdGet") {
            // uncomment below to test choresChoreIdGet
            //val choreId : kotlin.Int = 56 // kotlin.Int | A valid chore id
            //val result : ChoreDetailsResponse = apiInstance.choresChoreIdGet(choreId)
            //result shouldBe ("TODO")
        }

        // to test choresChoreIdPrintlabelGet
        should("test choresChoreIdPrintlabelGet") {
            // uncomment below to test choresChoreIdPrintlabelGet
            //val choreId : kotlin.Int = 56 // kotlin.Int | A valid chore id
            //val result : kotlin.String = apiInstance.choresChoreIdPrintlabelGet(choreId)
            //result shouldBe ("TODO")
        }

        // to test choresChoreIdToKeepMergeChoreIdToRemovePost
        should("test choresChoreIdToKeepMergeChoreIdToRemovePost") {
            // uncomment below to test choresChoreIdToKeepMergeChoreIdToRemovePost
            //val choreIdToKeep : kotlin.Int = 56 // kotlin.Int | A valid chore id of the chore to keep
            //val choreIdToRemove : kotlin.Int = 56 // kotlin.Int | A valid chore id of the chore to remove
            //apiInstance.choresChoreIdToKeepMergeChoreIdToRemovePost(choreIdToKeep, choreIdToRemove)
        }

        // to test choresExecutionsCalculateNextAssignmentsPost
        should("test choresExecutionsCalculateNextAssignmentsPost") {
            // uncomment below to test choresExecutionsCalculateNextAssignmentsPost
            //val choresExecutionsCalculateNextAssignmentsPostRequest : ChoresExecutionsCalculateNextAssignmentsPostRequest =  // ChoresExecutionsCalculateNextAssignmentsPostRequest | 
            //apiInstance.choresExecutionsCalculateNextAssignmentsPost(choresExecutionsCalculateNextAssignmentsPostRequest)
        }

        // to test choresExecutionsExecutionIdUndoPost
        should("test choresExecutionsExecutionIdUndoPost") {
            // uncomment below to test choresExecutionsExecutionIdUndoPost
            //val executionId : kotlin.Int = 56 // kotlin.Int | A valid chore execution id
            //apiInstance.choresExecutionsExecutionIdUndoPost(executionId)
        }

        // to test choresGet
        should("test choresGet") {
            // uncomment below to test choresGet
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<CurrentChoreResponse> = apiInstance.choresGet(query, order, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
