/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.FilesApi
import org.openapitools.client.models.Error400
import org.openapitools.client.models.FileGroups

class FilesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FilesApi
        //val apiInstance = FilesApi()

        // to test filesGroupFileNameDelete
        should("test filesGroupFileNameDelete") {
            // uncomment below to test filesGroupFileNameDelete
            //val group : FileGroups =  // FileGroups | The file group
            //val fileName : kotlin.String = fileName_example // kotlin.String | The file name (including extension)<br>**BASE64 encoded**
            //apiInstance.filesGroupFileNameDelete(group, fileName)
        }

        // to test filesGroupFileNameGet
        should("test filesGroupFileNameGet") {
            // uncomment below to test filesGroupFileNameGet
            //val group : FileGroups =  // FileGroups | The file group
            //val fileName : kotlin.String = fileName_example // kotlin.String | The file name (including extension)<br>**BASE64 encoded**
            //val forceServeAs : kotlin.String = forceServeAs_example // kotlin.String | Force the file to be served as the given type
            //val bestFitHeight : kotlin.Double = 8.14 // kotlin.Double | Only when using `force_serve_as` = `picture`: Downscale the picture to the given height while maintaining the aspect ratio
            //val bestFitWidth : kotlin.Double = 8.14 // kotlin.Double | Only when using `force_serve_as` = `picture`: Downscale the picture to the given width while maintaining the aspect ratio
            //val result : org.openapitools.client.infrastructure.OctetByteArray = apiInstance.filesGroupFileNameGet(group, fileName, forceServeAs, bestFitHeight, bestFitWidth)
            //result shouldBe ("TODO")
        }

        // to test filesGroupFileNamePut
        should("test filesGroupFileNamePut") {
            // uncomment below to test filesGroupFileNamePut
            //val group : FileGroups =  // FileGroups | The file group
            //val fileName : kotlin.String = fileName_example // kotlin.String | The file name (including extension)<br>**BASE64 encoded**
            //val body : org.openapitools.client.infrastructure.OctetByteArray = BINARY_DATA_HERE // org.openapitools.client.infrastructure.OctetByteArray | 
            //apiInstance.filesGroupFileNamePut(group, fileName, body)
        }

    }
}
