/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.GenericEntityInteractionsApi
import org.openapitools.client.models.Error400
import org.openapitools.client.models.Error500
import org.openapitools.client.models.ExposedEntityIncludingUserEntities
import org.openapitools.client.models.ExposedEntityIncludingUserEntitiesNotIncludingNotEditable
import org.openapitools.client.models.ExposedEntityNotIncludingNotDeletable
import org.openapitools.client.models.ExposedEntityNotIncludingNotEditable
import org.openapitools.client.models.ExposedEntityNotIncludingNotListable
import org.openapitools.client.models.ObjectsEntityGet200ResponseInner
import org.openapitools.client.models.ObjectsEntityPost200Response

class GenericEntityInteractionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GenericEntityInteractionsApi
        //val apiInstance = GenericEntityInteractionsApi()

        // to test objectsEntityGet
        should("test objectsEntityGet") {
            // uncomment below to test objectsEntityGet
            //val entity : ExposedEntityNotIncludingNotListable =  // ExposedEntityNotIncludingNotListable | A valid entity name
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<ObjectsEntityGet200ResponseInner> = apiInstance.objectsEntityGet(entity, query, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test objectsEntityObjectIdDelete
        should("test objectsEntityObjectIdDelete") {
            // uncomment below to test objectsEntityObjectIdDelete
            //val entity : ExposedEntityNotIncludingNotDeletable =  // ExposedEntityNotIncludingNotDeletable | A valid entity name
            //val objectId : kotlin.Int = 56 // kotlin.Int | A valid object id of the given entity
            //apiInstance.objectsEntityObjectIdDelete(entity, objectId)
        }

        // to test objectsEntityObjectIdGet
        should("test objectsEntityObjectIdGet") {
            // uncomment below to test objectsEntityObjectIdGet
            //val entity : ExposedEntityNotIncludingNotListable =  // ExposedEntityNotIncludingNotListable | A valid entity name
            //val objectId : kotlin.Int = 56 // kotlin.Int | A valid object id of the given entity
            //val result : ObjectsEntityGet200ResponseInner = apiInstance.objectsEntityObjectIdGet(entity, objectId)
            //result shouldBe ("TODO")
        }

        // to test objectsEntityObjectIdPut
        should("test objectsEntityObjectIdPut") {
            // uncomment below to test objectsEntityObjectIdPut
            //val entity : ExposedEntityNotIncludingNotEditable =  // ExposedEntityNotIncludingNotEditable | A valid entity name
            //val objectId : kotlin.Int = 56 // kotlin.Int | A valid object id of the given entity
            //val objectsEntityGet200ResponseInner : ObjectsEntityGet200ResponseInner =  // ObjectsEntityGet200ResponseInner | A valid entity object of the entity specified in parameter *entity*
            //apiInstance.objectsEntityObjectIdPut(entity, objectId, objectsEntityGet200ResponseInner)
        }

        // to test objectsEntityPost
        should("test objectsEntityPost") {
            // uncomment below to test objectsEntityPost
            //val entity : ExposedEntityNotIncludingNotEditable =  // ExposedEntityNotIncludingNotEditable | A valid entity name
            //val objectsEntityGet200ResponseInner : ObjectsEntityGet200ResponseInner =  // ObjectsEntityGet200ResponseInner | A valid entity object of the entity specified in parameter *entity*
            //val result : ObjectsEntityPost200Response = apiInstance.objectsEntityPost(entity, objectsEntityGet200ResponseInner)
            //result shouldBe ("TODO")
        }

        // to test userfieldsEntityObjectIdGet
        should("test userfieldsEntityObjectIdGet") {
            // uncomment below to test userfieldsEntityObjectIdGet
            //val entity : ExposedEntityIncludingUserEntities =  // ExposedEntityIncludingUserEntities | A valid entity name
            //val objectId : kotlin.String = objectId_example // kotlin.String | A valid object id of the given entity
            //val result : kotlin.String = apiInstance.userfieldsEntityObjectIdGet(entity, objectId)
            //result shouldBe ("TODO")
        }

        // to test userfieldsEntityObjectIdPut
        should("test userfieldsEntityObjectIdPut") {
            // uncomment below to test userfieldsEntityObjectIdPut
            //val entity : ExposedEntityIncludingUserEntitiesNotIncludingNotEditable =  // ExposedEntityIncludingUserEntitiesNotIncludingNotEditable | A valid entity name
            //val objectId : kotlin.String = objectId_example // kotlin.String | A valid object id of the given entity
            //val body : kotlin.Any =  // kotlin.Any | A valid entity object of the entity specified in parameter *entity*
            //apiInstance.userfieldsEntityObjectIdPut(entity, objectId, body)
        }

    }
}
