/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.PrintApi
import org.openapitools.client.models.Error400
import org.openapitools.client.models.PrintShoppinglistThermalGet200Response

class PrintApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PrintApi
        //val apiInstance = PrintApi()

        // to test printShoppinglistThermalGet
        should("test printShoppinglistThermalGet") {
            // uncomment below to test printShoppinglistThermalGet
            //val list : kotlin.Int = 56 // kotlin.Int | Shopping list id
            //val printHeader : kotlin.Boolean = true // kotlin.Boolean | Prints Grocy logo if true
            //val result : PrintShoppinglistThermalGet200Response = apiInstance.printShoppinglistThermalGet(list, printHeader)
            //result shouldBe ("TODO")
        }

    }
}
