/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.RecipesApi
import org.openapitools.client.models.Error400
import org.openapitools.client.models.Error500
import org.openapitools.client.models.RecipeFulfillmentResponse
import org.openapitools.client.models.RecipesRecipeIdAddNotFulfilledProductsToShoppinglistPostRequest
import org.openapitools.client.models.RecipesRecipeIdCopyPost200Response

class RecipesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecipesApi
        //val apiInstance = RecipesApi()

        // to test recipesFulfillmentGet
        should("test recipesFulfillmentGet") {
            // uncomment below to test recipesFulfillmentGet
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<RecipeFulfillmentResponse> = apiInstance.recipesFulfillmentGet(query, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test recipesRecipeIdAddNotFulfilledProductsToShoppinglistPost
        should("test recipesRecipeIdAddNotFulfilledProductsToShoppinglistPost") {
            // uncomment below to test recipesRecipeIdAddNotFulfilledProductsToShoppinglistPost
            //val recipeId : kotlin.String = recipeId_example // kotlin.String | A valid recipe id
            //val recipesRecipeIdAddNotFulfilledProductsToShoppinglistPostRequest : RecipesRecipeIdAddNotFulfilledProductsToShoppinglistPostRequest =  // RecipesRecipeIdAddNotFulfilledProductsToShoppinglistPostRequest | 
            //apiInstance.recipesRecipeIdAddNotFulfilledProductsToShoppinglistPost(recipeId, recipesRecipeIdAddNotFulfilledProductsToShoppinglistPostRequest)
        }

        // to test recipesRecipeIdConsumePost
        should("test recipesRecipeIdConsumePost") {
            // uncomment below to test recipesRecipeIdConsumePost
            //val recipeId : kotlin.String = recipeId_example // kotlin.String | A valid recipe id
            //apiInstance.recipesRecipeIdConsumePost(recipeId)
        }

        // to test recipesRecipeIdCopyPost
        should("test recipesRecipeIdCopyPost") {
            // uncomment below to test recipesRecipeIdCopyPost
            //val recipeId : kotlin.Int = 56 // kotlin.Int | A valid recipe id of the recipe to copy
            //val result : RecipesRecipeIdCopyPost200Response = apiInstance.recipesRecipeIdCopyPost(recipeId)
            //result shouldBe ("TODO")
        }

        // to test recipesRecipeIdFulfillmentGet
        should("test recipesRecipeIdFulfillmentGet") {
            // uncomment below to test recipesRecipeIdFulfillmentGet
            //val recipeId : kotlin.String = recipeId_example // kotlin.String | A valid recipe id
            //val result : RecipeFulfillmentResponse = apiInstance.recipesRecipeIdFulfillmentGet(recipeId)
            //result shouldBe ("TODO")
        }

        // to test recipesRecipeIdPrintlabelGet
        should("test recipesRecipeIdPrintlabelGet") {
            // uncomment below to test recipesRecipeIdPrintlabelGet
            //val recipeId : kotlin.Int = 56 // kotlin.Int | A valid recipe id
            //val result : kotlin.String = apiInstance.recipesRecipeIdPrintlabelGet(recipeId)
            //result shouldBe ("TODO")
        }

    }
}
