/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.StockByBarcodeApi
import org.openapitools.client.models.Error400
import org.openapitools.client.models.ProductDetailsResponse
import org.openapitools.client.models.StockLogEntry
import org.openapitools.client.models.StockProductsByBarcodeBarcodeAddPostRequest
import org.openapitools.client.models.StockProductsByBarcodeBarcodeConsumePostRequest
import org.openapitools.client.models.StockProductsByBarcodeBarcodeInventoryPostRequest
import org.openapitools.client.models.StockProductsByBarcodeBarcodeOpenPostRequest
import org.openapitools.client.models.StockProductsProductIdTransferPostRequest

class StockByBarcodeApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockByBarcodeApi
        //val apiInstance = StockByBarcodeApi()

        // to test stockProductsByBarcodeBarcodeAddPost
        should("test stockProductsByBarcodeBarcodeAddPost") {
            // uncomment below to test stockProductsByBarcodeBarcodeAddPost
            //val barcode : kotlin.String = barcode_example // kotlin.String | Barcode
            //val stockProductsByBarcodeBarcodeAddPostRequest : StockProductsByBarcodeBarcodeAddPostRequest =  // StockProductsByBarcodeBarcodeAddPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsByBarcodeBarcodeAddPost(barcode, stockProductsByBarcodeBarcodeAddPostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsByBarcodeBarcodeConsumePost
        should("test stockProductsByBarcodeBarcodeConsumePost") {
            // uncomment below to test stockProductsByBarcodeBarcodeConsumePost
            //val barcode : kotlin.String = barcode_example // kotlin.String | Barcode
            //val stockProductsByBarcodeBarcodeConsumePostRequest : StockProductsByBarcodeBarcodeConsumePostRequest =  // StockProductsByBarcodeBarcodeConsumePostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsByBarcodeBarcodeConsumePost(barcode, stockProductsByBarcodeBarcodeConsumePostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsByBarcodeBarcodeGet
        should("test stockProductsByBarcodeBarcodeGet") {
            // uncomment below to test stockProductsByBarcodeBarcodeGet
            //val barcode : kotlin.String = barcode_example // kotlin.String | Barcode
            //val result : ProductDetailsResponse = apiInstance.stockProductsByBarcodeBarcodeGet(barcode)
            //result shouldBe ("TODO")
        }

        // to test stockProductsByBarcodeBarcodeInventoryPost
        should("test stockProductsByBarcodeBarcodeInventoryPost") {
            // uncomment below to test stockProductsByBarcodeBarcodeInventoryPost
            //val barcode : kotlin.String = barcode_example // kotlin.String | Barcode
            //val stockProductsByBarcodeBarcodeInventoryPostRequest : StockProductsByBarcodeBarcodeInventoryPostRequest =  // StockProductsByBarcodeBarcodeInventoryPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsByBarcodeBarcodeInventoryPost(barcode, stockProductsByBarcodeBarcodeInventoryPostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsByBarcodeBarcodeOpenPost
        should("test stockProductsByBarcodeBarcodeOpenPost") {
            // uncomment below to test stockProductsByBarcodeBarcodeOpenPost
            //val barcode : kotlin.String = barcode_example // kotlin.String | Barcode
            //val stockProductsByBarcodeBarcodeOpenPostRequest : StockProductsByBarcodeBarcodeOpenPostRequest =  // StockProductsByBarcodeBarcodeOpenPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsByBarcodeBarcodeOpenPost(barcode, stockProductsByBarcodeBarcodeOpenPostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsByBarcodeBarcodeTransferPost
        should("test stockProductsByBarcodeBarcodeTransferPost") {
            // uncomment below to test stockProductsByBarcodeBarcodeTransferPost
            //val barcode : kotlin.String = barcode_example // kotlin.String | Barcode
            //val stockProductsProductIdTransferPostRequest : StockProductsProductIdTransferPostRequest =  // StockProductsProductIdTransferPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsByBarcodeBarcodeTransferPost(barcode, stockProductsProductIdTransferPostRequest)
            //result shouldBe ("TODO")
        }

    }
}
