/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.specs.ShouldSpec

class StockApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StockApi
        //val apiInstance = StockApi()

        // to test stockBarcodesExternalLookupBarcodeGet
        should("test stockBarcodesExternalLookupBarcodeGet") {
            // uncomment below to test stockBarcodesExternalLookupBarcodeGet
            //val barcode : kotlin.String = barcode_example // kotlin.String | The barcode to lookup up
            //val add : kotlin.Int = true // kotlin.Int | When true, the product is added to the database on a successful lookup and the new product id is in included in the response
            //val result : ExternalBarcodeLookupResponse = apiInstance.stockBarcodesExternalLookupBarcodeGet(barcode, add)
            //result shouldBe ("TODO")
        }

        // to test stockBookingsBookingIdGet
        should("test stockBookingsBookingIdGet") {
            // uncomment below to test stockBookingsBookingIdGet
            //val bookingId : kotlin.Int = 56 // kotlin.Int | A valid stock booking id
            //val result : StockLogEntry = apiInstance.stockBookingsBookingIdGet(bookingId)
            //result shouldBe ("TODO")
        }

        // to test stockBookingsBookingIdUndoPost
        should("test stockBookingsBookingIdUndoPost") {
            // uncomment below to test stockBookingsBookingIdUndoPost
            //val bookingId : kotlin.Int = 56 // kotlin.Int | A valid stock booking id
            //apiInstance.stockBookingsBookingIdUndoPost(bookingId)
        }

        // to test stockEntryEntryIdGet
        should("test stockEntryEntryIdGet") {
            // uncomment below to test stockEntryEntryIdGet
            //val entryId : kotlin.Int = 56 // kotlin.Int | A valid stock entry id
            //val result : StockEntry = apiInstance.stockEntryEntryIdGet(entryId)
            //result shouldBe ("TODO")
        }

        // to test stockEntryEntryIdPrintlabelGet
        should("test stockEntryEntryIdPrintlabelGet") {
            // uncomment below to test stockEntryEntryIdPrintlabelGet
            //val entryId : kotlin.Int = 56 // kotlin.Int | A valid stock entry id
            //val result : kotlin.String = apiInstance.stockEntryEntryIdPrintlabelGet(entryId)
            //result shouldBe ("TODO")
        }

        // to test stockEntryEntryIdPut
        should("test stockEntryEntryIdPut") {
            // uncomment below to test stockEntryEntryIdPut
            //val entryId : kotlin.Int = 56 // kotlin.Int | A valid stock entry id
            //val stockEntryEntryIdPutRequest : StockEntryEntryIdPutRequest =  // StockEntryEntryIdPutRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockEntryEntryIdPut(entryId, stockEntryEntryIdPutRequest)
            //result shouldBe ("TODO")
        }

        // to test stockGet
        should("test stockGet") {
            // uncomment below to test stockGet
            //val result : kotlin.collections.List<CurrentStockResponse> = apiInstance.stockGet()
            //result shouldBe ("TODO")
        }

        // to test stockLocationsLocationIdEntriesGet
        should("test stockLocationsLocationIdEntriesGet") {
            // uncomment below to test stockLocationsLocationIdEntriesGet
            //val locationId : kotlin.Int = 56 // kotlin.Int | A valid location id
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<StockEntry> = apiInstance.stockLocationsLocationIdEntriesGet(locationId, query, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdAddPost
        should("test stockProductsProductIdAddPost") {
            // uncomment below to test stockProductsProductIdAddPost
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val stockProductsProductIdAddPostRequest : StockProductsProductIdAddPostRequest =  // StockProductsProductIdAddPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsProductIdAddPost(productId, stockProductsProductIdAddPostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdConsumePost
        should("test stockProductsProductIdConsumePost") {
            // uncomment below to test stockProductsProductIdConsumePost
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val stockProductsProductIdConsumePostRequest : StockProductsProductIdConsumePostRequest =  // StockProductsProductIdConsumePostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsProductIdConsumePost(productId, stockProductsProductIdConsumePostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdEntriesGet
        should("test stockProductsProductIdEntriesGet") {
            // uncomment below to test stockProductsProductIdEntriesGet
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val includeSubProducts : kotlin.Int = true // kotlin.Int | If sub products should be included (if the given product is a parent product and in addition to the ones of the given product)
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<StockEntry> = apiInstance.stockProductsProductIdEntriesGet(productId, includeSubProducts, query, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdGet
        should("test stockProductsProductIdGet") {
            // uncomment below to test stockProductsProductIdGet
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val result : ProductDetailsResponse = apiInstance.stockProductsProductIdGet(productId)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdInventoryPost
        should("test stockProductsProductIdInventoryPost") {
            // uncomment below to test stockProductsProductIdInventoryPost
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val stockProductsProductIdInventoryPostRequest : StockProductsProductIdInventoryPostRequest =  // StockProductsProductIdInventoryPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsProductIdInventoryPost(productId, stockProductsProductIdInventoryPostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdLocationsGet
        should("test stockProductsProductIdLocationsGet") {
            // uncomment below to test stockProductsProductIdLocationsGet
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val includeSubProducts : kotlin.Int = true // kotlin.Int | If sub product locations should be included (if the given product is a parent product and in addition to the ones of the given product)
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<StockLocation> = apiInstance.stockProductsProductIdLocationsGet(productId, includeSubProducts, query, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdOpenPost
        should("test stockProductsProductIdOpenPost") {
            // uncomment below to test stockProductsProductIdOpenPost
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val stockProductsProductIdOpenPostRequest : StockProductsProductIdOpenPostRequest =  // StockProductsProductIdOpenPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsProductIdOpenPost(productId, stockProductsProductIdOpenPostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdPriceHistoryGet
        should("test stockProductsProductIdPriceHistoryGet") {
            // uncomment below to test stockProductsProductIdPriceHistoryGet
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val result : kotlin.collections.List<ProductPriceHistory> = apiInstance.stockProductsProductIdPriceHistoryGet(productId)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdPrintlabelGet
        should("test stockProductsProductIdPrintlabelGet") {
            // uncomment below to test stockProductsProductIdPrintlabelGet
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val result : kotlin.String = apiInstance.stockProductsProductIdPrintlabelGet(productId)
            //result shouldBe ("TODO")
        }

        // to test stockProductsProductIdToKeepMergeProductIdToRemovePost
        should("test stockProductsProductIdToKeepMergeProductIdToRemovePost") {
            // uncomment below to test stockProductsProductIdToKeepMergeProductIdToRemovePost
            //val productIdToKeep : kotlin.Int = 56 // kotlin.Int | A valid product id of the product to keep
            //val productIdToRemove : kotlin.Int = 56 // kotlin.Int | A valid product id of the product to remove
            //apiInstance.stockProductsProductIdToKeepMergeProductIdToRemovePost(productIdToKeep, productIdToRemove)
        }

        // to test stockProductsProductIdTransferPost
        should("test stockProductsProductIdTransferPost") {
            // uncomment below to test stockProductsProductIdTransferPost
            //val productId : kotlin.Int = 56 // kotlin.Int | A valid product id
            //val stockProductsProductIdTransferPostRequest : StockProductsProductIdTransferPostRequest =  // StockProductsProductIdTransferPostRequest | 
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockProductsProductIdTransferPost(productId, stockProductsProductIdTransferPostRequest)
            //result shouldBe ("TODO")
        }

        // to test stockShoppinglistAddExpiredProductsPost
        should("test stockShoppinglistAddExpiredProductsPost") {
            // uncomment below to test stockShoppinglistAddExpiredProductsPost
            //val stockShoppinglistAddMissingProductsPostRequest : StockShoppinglistAddMissingProductsPostRequest =  // StockShoppinglistAddMissingProductsPostRequest | 
            //apiInstance.stockShoppinglistAddExpiredProductsPost(stockShoppinglistAddMissingProductsPostRequest)
        }

        // to test stockShoppinglistAddMissingProductsPost
        should("test stockShoppinglistAddMissingProductsPost") {
            // uncomment below to test stockShoppinglistAddMissingProductsPost
            //val stockShoppinglistAddMissingProductsPostRequest : StockShoppinglistAddMissingProductsPostRequest =  // StockShoppinglistAddMissingProductsPostRequest | 
            //apiInstance.stockShoppinglistAddMissingProductsPost(stockShoppinglistAddMissingProductsPostRequest)
        }

        // to test stockShoppinglistAddOverdueProductsPost
        should("test stockShoppinglistAddOverdueProductsPost") {
            // uncomment below to test stockShoppinglistAddOverdueProductsPost
            //val stockShoppinglistAddMissingProductsPostRequest : StockShoppinglistAddMissingProductsPostRequest =  // StockShoppinglistAddMissingProductsPostRequest | 
            //apiInstance.stockShoppinglistAddOverdueProductsPost(stockShoppinglistAddMissingProductsPostRequest)
        }

        // to test stockShoppinglistAddProductPost
        should("test stockShoppinglistAddProductPost") {
            // uncomment below to test stockShoppinglistAddProductPost
            //val stockShoppinglistAddProductPostRequest : StockShoppinglistAddProductPostRequest =  // StockShoppinglistAddProductPostRequest | 
            //apiInstance.stockShoppinglistAddProductPost(stockShoppinglistAddProductPostRequest)
        }

        // to test stockShoppinglistClearPost
        should("test stockShoppinglistClearPost") {
            // uncomment below to test stockShoppinglistClearPost
            //val stockShoppinglistClearPostRequest : StockShoppinglistClearPostRequest =  // StockShoppinglistClearPostRequest | 
            //apiInstance.stockShoppinglistClearPost(stockShoppinglistClearPostRequest)
        }

        // to test stockShoppinglistRemoveProductPost
        should("test stockShoppinglistRemoveProductPost") {
            // uncomment below to test stockShoppinglistRemoveProductPost
            //val stockShoppinglistRemoveProductPostRequest : StockShoppinglistRemoveProductPostRequest =  // StockShoppinglistRemoveProductPostRequest | 
            //apiInstance.stockShoppinglistRemoveProductPost(stockShoppinglistRemoveProductPostRequest)
        }

        // to test stockTransactionsTransactionIdGet
        should("test stockTransactionsTransactionIdGet") {
            // uncomment below to test stockTransactionsTransactionIdGet
            //val transactionId : kotlin.String = transactionId_example // kotlin.String | A valid stock transaction id
            //val result : kotlin.collections.List<StockLogEntry> = apiInstance.stockTransactionsTransactionIdGet(transactionId)
            //result shouldBe ("TODO")
        }

        // to test stockTransactionsTransactionIdUndoPost
        should("test stockTransactionsTransactionIdUndoPost") {
            // uncomment below to test stockTransactionsTransactionIdUndoPost
            //val transactionId : kotlin.String = transactionId_example // kotlin.String | A valid stock transaction id
            //apiInstance.stockTransactionsTransactionIdUndoPost(transactionId)
        }

        // to test stockVolatileGet
        should("test stockVolatileGet") {
            // uncomment below to test stockVolatileGet
            //val dueSoonDays : kotlin.Int = 56 // kotlin.Int | The number of days in which products are considered to be due soon
            //val result : CurrentVolatilStockResponse = apiInstance.stockVolatileGet(dueSoonDays)
            //result shouldBe ("TODO")
        }

    }
}
