/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SystemApi
import org.openapitools.client.models.DbChangedTimeResponse
import org.openapitools.client.models.Error400
import org.openapitools.client.models.MissingLocalizationRequest
import org.openapitools.client.models.SystemInfoGet200Response
import org.openapitools.client.models.TimeResponse

class SystemApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemApi
        //val apiInstance = SystemApi()

        // to test systemConfigGet
        should("test systemConfigGet") {
            // uncomment below to test systemConfigGet
            //val result : kotlin.String = apiInstance.systemConfigGet()
            //result shouldBe ("TODO")
        }

        // to test systemDbChangedTimeGet
        should("test systemDbChangedTimeGet") {
            // uncomment below to test systemDbChangedTimeGet
            //val result : DbChangedTimeResponse = apiInstance.systemDbChangedTimeGet()
            //result shouldBe ("TODO")
        }

        // to test systemInfoGet
        should("test systemInfoGet") {
            // uncomment below to test systemInfoGet
            //val result : SystemInfoGet200Response = apiInstance.systemInfoGet()
            //result shouldBe ("TODO")
        }

        // to test systemLocalizationStringsGet
        should("test systemLocalizationStringsGet") {
            // uncomment below to test systemLocalizationStringsGet
            //val result : kotlin.String = apiInstance.systemLocalizationStringsGet()
            //result shouldBe ("TODO")
        }

        // to test systemLogMissingLocalizationPost
        should("test systemLogMissingLocalizationPost") {
            // uncomment below to test systemLogMissingLocalizationPost
            //val missingLocalizationRequest : MissingLocalizationRequest =  // MissingLocalizationRequest | A valid MissingLocalizationRequest object
            //apiInstance.systemLogMissingLocalizationPost(missingLocalizationRequest)
        }

        // to test systemTimeGet
        should("test systemTimeGet") {
            // uncomment below to test systemTimeGet
            //val offset : kotlin.Int = 56 // kotlin.Int | Offset of timestamp in seconds. Can be positive or negative.
            //val result : TimeResponse = apiInstance.systemTimeGet(offset)
            //result shouldBe ("TODO")
        }

    }
}
