/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.TasksApi
import org.openapitools.client.models.CurrentTaskResponse
import org.openapitools.client.models.Error400
import org.openapitools.client.models.Error500
import org.openapitools.client.models.TasksTaskIdCompletePostRequest

class TasksApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TasksApi
        //val apiInstance = TasksApi()

        // to test tasksGet
        should("test tasksGet") {
            // uncomment below to test tasksGet
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<CurrentTaskResponse> = apiInstance.tasksGet(query, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test tasksTaskIdCompletePost
        should("test tasksTaskIdCompletePost") {
            // uncomment below to test tasksTaskIdCompletePost
            //val taskId : kotlin.Int = 56 // kotlin.Int | A valid task id
            //val tasksTaskIdCompletePostRequest : TasksTaskIdCompletePostRequest =  // TasksTaskIdCompletePostRequest | 
            //apiInstance.tasksTaskIdCompletePost(taskId, tasksTaskIdCompletePostRequest)
        }

        // to test tasksTaskIdUndoPost
        should("test tasksTaskIdUndoPost") {
            // uncomment below to test tasksTaskIdUndoPost
            //val taskId : kotlin.Int = 56 // kotlin.Int | A valid task id
            //apiInstance.tasksTaskIdUndoPost(taskId)
        }

    }
}
