/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.UserManagementApi
import org.openapitools.client.models.Error400
import org.openapitools.client.models.Error500
import org.openapitools.client.models.User
import org.openapitools.client.models.UserDto
import org.openapitools.client.models.UsersUserIdPermissionsGet200ResponseInner
import org.openapitools.client.models.UsersUserIdPermissionsPostRequest
import org.openapitools.client.models.UsersUserIdPermissionsPutRequest

class UserManagementApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserManagementApi
        //val apiInstance = UserManagementApi()

        // to test usersGet
        should("test usersGet") {
            // uncomment below to test usersGet
            //val query : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | An array of filter conditions, each of them is a string in the form of `<field><condition><value>` where<br>`<field>` is a valid field name<br>`<condition>` is a comparison operator, one of<br>&nbsp;&nbsp;`=` equal<br>&nbsp;&nbsp;`!=` not equal<br>&nbsp;&nbsp;`~` LIKE<br>&nbsp;&nbsp;`!~` not LIKE<br>&nbsp;&nbsp;`<` less<br>&nbsp;&nbsp;`>` greater<br>&nbsp;&nbsp;`<=` less or equal<br>&nbsp;&nbsp;`>=` greater or equal<br>&nbsp;&nbsp;`§` regular expression<br>`<value>` is the value to search for
            //val order : kotlin.String = order_example // kotlin.String | A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)
            //val limit : kotlin.Int = 56 // kotlin.Int | The maximum number of objects to return
            //val offset : kotlin.Int = 56 // kotlin.Int | The number of objects to skip
            //val result : kotlin.collections.List<UserDto> = apiInstance.usersGet(query, order, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test usersPost
        should("test usersPost") {
            // uncomment below to test usersPost
            //val user : User =  // User | A valid user object
            //apiInstance.usersPost(user)
        }

        // to test usersUserIdDelete
        should("test usersUserIdDelete") {
            // uncomment below to test usersUserIdDelete
            //val userId : kotlin.Int = 56 // kotlin.Int | A valid user id
            //apiInstance.usersUserIdDelete(userId)
        }

        // to test usersUserIdPermissionsGet
        should("test usersUserIdPermissionsGet") {
            // uncomment below to test usersUserIdPermissionsGet
            //val userId : kotlin.Int = 56 // kotlin.Int | A valid user id
            //val result : kotlin.collections.List<UsersUserIdPermissionsGet200ResponseInner> = apiInstance.usersUserIdPermissionsGet(userId)
            //result shouldBe ("TODO")
        }

        // to test usersUserIdPermissionsPost
        should("test usersUserIdPermissionsPost") {
            // uncomment below to test usersUserIdPermissionsPost
            //val userId : kotlin.Int = 56 // kotlin.Int | A valid user id
            //val usersUserIdPermissionsPostRequest : UsersUserIdPermissionsPostRequest =  // UsersUserIdPermissionsPostRequest | 
            //apiInstance.usersUserIdPermissionsPost(userId, usersUserIdPermissionsPostRequest)
        }

        // to test usersUserIdPermissionsPut
        should("test usersUserIdPermissionsPut") {
            // uncomment below to test usersUserIdPermissionsPut
            //val userId : kotlin.Int = 56 // kotlin.Int | A valid user id
            //val usersUserIdPermissionsPutRequest : UsersUserIdPermissionsPutRequest =  // UsersUserIdPermissionsPutRequest | 
            //apiInstance.usersUserIdPermissionsPut(userId, usersUserIdPermissionsPutRequest)
        }

        // to test usersUserIdPut
        should("test usersUserIdPut") {
            // uncomment below to test usersUserIdPut
            //val userId : kotlin.Int = 56 // kotlin.Int | A valid user id
            //val user : User =  // User | A valid user object
            //apiInstance.usersUserIdPut(userId, user)
        }

    }
}
