/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.client.apis

import org.openapitools.client.models.Error400
import org.openapitools.client.models.ProductDetailsResponse
import org.openapitools.client.models.StockLogEntry
import org.openapitools.client.models.StockProductsByBarcodeBarcodeAddPostRequest
import org.openapitools.client.models.StockProductsByBarcodeBarcodeConsumePostRequest
import org.openapitools.client.models.StockProductsByBarcodeBarcodeInventoryPostRequest
import org.openapitools.client.models.StockProductsByBarcodeBarcodeOpenPostRequest
import org.openapitools.client.models.StockProductsProductIdTransferPostRequest

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class StockByBarcodeApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Adds the given amount of the by its barcode given product to stock
     * 
     * @param barcode Barcode
     * @param stockProductsByBarcodeBarcodeAddPostRequest 
     * @return kotlin.collections.List<StockLogEntry>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun stockProductsByBarcodeBarcodeAddPost(barcode: kotlin.String, stockProductsByBarcodeBarcodeAddPostRequest: StockProductsByBarcodeBarcodeAddPostRequest): HttpResponse<kotlin.collections.List<StockLogEntry>> {

        val localVariableAuthNames = listOf<String>("ApiKeyAuth")

        val localVariableBody = stockProductsByBarcodeBarcodeAddPostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/stock/products/by-barcode/{barcode}/add".replace("{" + "barcode" + "}", "$barcode"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<StockProductsByBarcodeBarcodeAddPostResponse>().map { value }
    }


    @Serializable(StockProductsByBarcodeBarcodeAddPostResponse.Companion::class)
    private class StockProductsByBarcodeBarcodeAddPostResponse(val value: List<StockLogEntry>) {
        companion object : KSerializer<StockProductsByBarcodeBarcodeAddPostResponse> {
            private val serializer: KSerializer<List<StockLogEntry>> = serializer<List<StockLogEntry>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: StockProductsByBarcodeBarcodeAddPostResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = StockProductsByBarcodeBarcodeAddPostResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Removes the given amount of the by its barcode given product from stock
     * 
     * @param barcode Barcode
     * @param stockProductsByBarcodeBarcodeConsumePostRequest 
     * @return kotlin.collections.List<StockLogEntry>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun stockProductsByBarcodeBarcodeConsumePost(barcode: kotlin.String, stockProductsByBarcodeBarcodeConsumePostRequest: StockProductsByBarcodeBarcodeConsumePostRequest): HttpResponse<kotlin.collections.List<StockLogEntry>> {

        val localVariableAuthNames = listOf<String>("ApiKeyAuth")

        val localVariableBody = stockProductsByBarcodeBarcodeConsumePostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/stock/products/by-barcode/{barcode}/consume".replace("{" + "barcode" + "}", "$barcode"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<StockProductsByBarcodeBarcodeConsumePostResponse>().map { value }
    }


    @Serializable(StockProductsByBarcodeBarcodeConsumePostResponse.Companion::class)
    private class StockProductsByBarcodeBarcodeConsumePostResponse(val value: List<StockLogEntry>) {
        companion object : KSerializer<StockProductsByBarcodeBarcodeConsumePostResponse> {
            private val serializer: KSerializer<List<StockLogEntry>> = serializer<List<StockLogEntry>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: StockProductsByBarcodeBarcodeConsumePostResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = StockProductsByBarcodeBarcodeConsumePostResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Returns details of the given product by its barcode
     * 
     * @param barcode Barcode
     * @return ProductDetailsResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun stockProductsByBarcodeBarcodeGet(barcode: kotlin.String): HttpResponse<ProductDetailsResponse> {

        val localVariableAuthNames = listOf<String>("ApiKeyAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/stock/products/by-barcode/{barcode}".replace("{" + "barcode" + "}", "$barcode"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Inventories the by its barcode given product (adds/removes based on the given new amount)
     * 
     * @param barcode Barcode
     * @param stockProductsByBarcodeBarcodeInventoryPostRequest 
     * @return kotlin.collections.List<StockLogEntry>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun stockProductsByBarcodeBarcodeInventoryPost(barcode: kotlin.String, stockProductsByBarcodeBarcodeInventoryPostRequest: StockProductsByBarcodeBarcodeInventoryPostRequest): HttpResponse<kotlin.collections.List<StockLogEntry>> {

        val localVariableAuthNames = listOf<String>("ApiKeyAuth")

        val localVariableBody = stockProductsByBarcodeBarcodeInventoryPostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/stock/products/by-barcode/{barcode}/inventory".replace("{" + "barcode" + "}", "$barcode"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<StockProductsByBarcodeBarcodeInventoryPostResponse>().map { value }
    }


    @Serializable(StockProductsByBarcodeBarcodeInventoryPostResponse.Companion::class)
    private class StockProductsByBarcodeBarcodeInventoryPostResponse(val value: List<StockLogEntry>) {
        companion object : KSerializer<StockProductsByBarcodeBarcodeInventoryPostResponse> {
            private val serializer: KSerializer<List<StockLogEntry>> = serializer<List<StockLogEntry>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: StockProductsByBarcodeBarcodeInventoryPostResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = StockProductsByBarcodeBarcodeInventoryPostResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Marks the given amount of the by its barcode given product as opened
     * 
     * @param barcode Barcode
     * @param stockProductsByBarcodeBarcodeOpenPostRequest 
     * @return kotlin.collections.List<StockLogEntry>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun stockProductsByBarcodeBarcodeOpenPost(barcode: kotlin.String, stockProductsByBarcodeBarcodeOpenPostRequest: StockProductsByBarcodeBarcodeOpenPostRequest): HttpResponse<kotlin.collections.List<StockLogEntry>> {

        val localVariableAuthNames = listOf<String>("ApiKeyAuth")

        val localVariableBody = stockProductsByBarcodeBarcodeOpenPostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/stock/products/by-barcode/{barcode}/open".replace("{" + "barcode" + "}", "$barcode"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<StockProductsByBarcodeBarcodeOpenPostResponse>().map { value }
    }


    @Serializable(StockProductsByBarcodeBarcodeOpenPostResponse.Companion::class)
    private class StockProductsByBarcodeBarcodeOpenPostResponse(val value: List<StockLogEntry>) {
        companion object : KSerializer<StockProductsByBarcodeBarcodeOpenPostResponse> {
            private val serializer: KSerializer<List<StockLogEntry>> = serializer<List<StockLogEntry>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: StockProductsByBarcodeBarcodeOpenPostResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = StockProductsByBarcodeBarcodeOpenPostResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Transfers the given amount of the by its barcode given product from one location to another (this is currently not supported for tare weight handling enabled products)
     * 
     * @param barcode Barcode
     * @param stockProductsProductIdTransferPostRequest 
     * @return kotlin.collections.List<StockLogEntry>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun stockProductsByBarcodeBarcodeTransferPost(barcode: kotlin.String, stockProductsProductIdTransferPostRequest: StockProductsProductIdTransferPostRequest): HttpResponse<kotlin.collections.List<StockLogEntry>> {

        val localVariableAuthNames = listOf<String>("ApiKeyAuth")

        val localVariableBody = stockProductsProductIdTransferPostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/stock/products/by-barcode/{barcode}/transfer".replace("{" + "barcode" + "}", "$barcode"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<StockProductsByBarcodeBarcodeTransferPostResponse>().map { value }
    }


    @Serializable(StockProductsByBarcodeBarcodeTransferPostResponse.Companion::class)
    private class StockProductsByBarcodeBarcodeTransferPostResponse(val value: List<StockLogEntry>) {
        companion object : KSerializer<StockProductsByBarcodeBarcodeTransferPostResponse> {
            private val serializer: KSerializer<List<StockLogEntry>> = serializer<List<StockLogEntry>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: StockProductsByBarcodeBarcodeTransferPostResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = StockProductsByBarcodeBarcodeTransferPostResponse(serializer.deserialize(decoder))
        }
    }

}
